### ISSUE TITLE
Saving long description of Team Profile doesn't work

### ISSUE THREAD

**Issue by toli** [docker/hub-beta-feedback#1]
Under `Organizations and Teams`, select a team, go to `Profile` and go to change `Description`

changes don't seem to be saved - when you got o a different tab and come back, the changes are not persisted

![hub-beta](https://cloud.githubusercontent.com/assets/34369/7973381/959471b0-0a09-11e5-8e67-5aa4a3a7a46f.gif)

**Comment by ChristopherBiscardi** [comment]
This should be fixed on next deploy. Our base image was missing the patch call.

**Comment by ChristopherBiscardi** [comment]
Verified fix on beta. Closing.
