### ISSUE TITLE
Login form - overlapping labels

### ISSUE THREAD

**Issue by mariokostelac** [docker/hub-beta-feedback#100]
I can't reproduce the bug (I know it sucks), but got something from screenshot.
https://www.evernote.com/l/AFJ0kEJeW1ROiK6HgFAOugJfk8Jsh9b2FT8

OS: OS X 10.10.3
Browser: Chrome Version 43.0.2357.124 (64-bit)

**Comment by ChristopherBiscardi** [comment]
Closing as dupe of #93
