### ISSUE TITLE
No github repository link ?

### ISSUE THREAD

**Issue by juanluisbaptiste** [docker/hub-beta-feedback#101]
Hi,

I don't see anywhere a link to see the github repo from where the Dockerfile us pulled from like in the current hub site. I hope you add it back, it's very useful to be able to browse the github repo to see any other files that are part of the Dockerfile.

**Comment by rrarunan** [comment]
@juanluisbaptiste Can you provide an example of where? For eg. this official mongodb repo `https://hub-beta.docker.com/_/mongo/` this repo has the links to the dockerfile in github. Is this what you are talking about or is it for a user created repo?

**Comment by juanluisbaptiste** [comment]
@rrarunan I think you didn't understand me, I don't mean the links to the Dockerfile at the github repo, but a link to the whole github repo like the current hub has. The mongodb repo you show doesn't have that either, it has a link to the github repo as part of the description, but that's not what I mean. For example:

On this repo at the current hub you can see a link to the right under the BUILD section that says "Source Project Page" that takes you to the repo's github page:

https://registry.hub.docker.com/u/juanluisbaptiste/bigbluebutton/

The new hub doesn't have that: 

https://hub-beta.docker.com/r/juanluisbaptiste/bigbluebutton/

So, the only way now to get to github repo is to search directly for it on github.

**Comment by rrarunan** [comment]
@juanluisbaptiste Cool. Got it. Yes, that's a good catch. Thanks for reporting!

**Comment by ahmetalpbalkan** [comment]
+1

Can't reach to Github repo from Docker image

![image](https://cloud.githubusercontent.com/assets/159209/8393259/2154c496-1cbd-11e5-9919-44e7ff9c3f61.png)

**Comment by rrarunan** [comment]
Ok, this issue is fixed. There are other related minor issues: #288 that are still being tracked and addressed.
