### ISSUE TITLE
Images in README.md not being rendered

### ISSUE THREAD

**Issue by hairyhenderson** [docker/hub-beta-feedback#104]
This works on the previous Hub:

https://registry.hub.docker.com/u/hairyhenderson/f1foo/
![screenshot 2015-06-19 20 01 49](https://cloud.githubusercontent.com/assets/2037086/8265038/2c4bb51c-16be-11e5-9296-d48e7c27ab1e.png)

But not on the beta hub:

https://hub-beta.docker.com/r/hairyhenderson/f1foo/
![screenshot 2015-06-19 20 03 24](https://cloud.githubusercontent.com/assets/2037086/8265048/42f1feca-16be-11e5-85a5-20a21bc1a649.png)

**Comment by ruffsl** [comment]
I am seeing this for both some links and all images as well.

## Information
* Operating system: Ubuntu 14.04 LTS
* Browser and Browser version: Firefox Version 39.0 (64-bit)
* URL for the page in question
 * https://hub-beta.docker.com/_/ros/
 * https://registry.hub.docker.com/_/ros/
* Screenshots of the issue (if applicable)
![image](https://cloud.githubusercontent.com/assets/2293573/9098009/0d72d926-3b7c-11e5-9c92-393fa952af73.png)
![image](https://cloud.githubusercontent.com/assets/2293573/9098165/eed81c5a-3b7c-11e5-8a87-2b02ea6617da.png)
* Any error messages (on screen or in browser console)
```
The site specified an invalid Strict-Transport-Security header.[Learn More] ros
This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] forms2.min.js
The site specified an invalid Strict-Transport-Security header.[Learn More] main.css
The site specified an invalid Strict-Transport-Security header.[Learn More] client.e933f746fba1702faf97.js
The site specified an invalid Strict-Transport-Security header.[Learn More] main-0-e933f746fba1702faf97.css
The site specified an invalid Strict-Transport-Security header.[Learn More] font-awesome.min.css
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create client.e933f746fba1702faf97.js:19:29971
"Warning: Failed propType: Invalid prop `lastUpdated` of type `string` supplied to `t`, expected `boolean`. Check the render method of `tStoreConnector`." client.e933f746fba1702faf97.js:1:15690
"Warning: Failed propType: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`. Check the render method of `RepositoryDetails`." client.e933f746fba1702faf97.js:1:15690
"Warning: Failed propType: Required prop `next` was not specified in `Pagination`. Check the render method of `RepoComments`." client.e933f746fba1702faf97.js:1:15690
"Warning: Failed propType: Required prop `prev` was not specified in `Pagination`. Check the render method of `RepoComments`." client.e933f746fba1702faf97.js:1:15690
The site specified an invalid Strict-Transport-Security header.[Learn More] mini-logo-white-inset.png
The site specified an invalid Strict-Transport-Security header.[Learn More] mini-logo.svg
Security wrapper denied access to property _gaUserPrefs on privileged Javascript object. Support for exposing privileged objects to untrusted content via __exposedProps__ is being gradually removed - use WebIDL bindings or Components.utils.cloneInto instead. Note that only the first denied property access from a given global object will be reported. analytics.js:4:0
```
* The rough date and time the error occurred (be sure to include your time zone)
 * 2:17 PM Wednesday, August 5, 2015 (PDT)

As a side note, I'm not so much a fan of the poorer contrast with the light blue everywhere on a white background; makes it slightly harder to read.

**Comment by rrarunan** [comment]
The issue of images not loading should be fixed. Although we have other markdown related issues, we are tracking and fixing: #225, #195, #164, #88, #124, #179.
