### ISSUE TITLE
Screen freezes when attempting to login

### ISSUE THREAD

**Issue by j0hnst0n** [docker/hub-beta-feedback#105]
After hitting submit, screen freezes for 1-2 min, then I'm bounced back to hub-beta.docker.com homepage.

![image](https://cloud.githubusercontent.com/assets/1610391/8271604/042c6b40-17d5-11e5-84d4-f29075727b8b.png)

**Comment by nhsiehgit** [comment]
@j0hnst0n So you aren't actually able to login? or it just hangs for a bit before logging you in?

I'm not having this issue.  Is it blocking you from taking any other actions while attempting to log you in?

**Comment by ChristopherBiscardi** [comment]
We were having an issue yesterday as we swapped to new infra where some of the APIs were consistently 504ing in the old deployment. I've confirmed that this is what's happening here and will make sure it clears up.
