### ISSUE TITLE
Password reset link sent via email errors out

### ISSUE THREAD

**Issue by ksasi** [docker/hub-beta-feedback#107]
Hi,

The link in the email which we receive to reset the password after clicking on "forgot password?" in https://hub-beta.docker.com/login/ errors out. It gives the below error

502 Bad Gateway
nginx

![screen shot 2015-06-23 at 1 19 32 am](https://cloud.githubusercontent.com/assets/7089391/8299925/b5bd44f4-1944-11e5-8b0b-2797faffc524.png)

**Comment by ChristopherBiscardi** [comment]
I've successfully reproduced this.

In this meantime, if you need to reset your password you can do that on the [old hub here](https://hub.docker.com/account/forgot-password/)

**Comment by ChristopherBiscardi** [comment]
Fix is deployed.
