### ISSUE TITLE
Markdown tables difficult to read

### ISSUE THREAD

**Issue by nchazlett** [docker/hub-beta-feedback#113]
The color scheme for background and font color is making text in table cells difficult to read.

Here is an example from https://hub-beta.docker.com/r/lgautier/railroadtracks/:

![screen shot 2015-06-24 at 8 25 41 pm](https://cloud.githubusercontent.com/assets/6706049/8344438/aace6516-1aaf-11e5-9289-8d284474310f.png)

**Comment by ChristopherBiscardi** [comment]
We swapped out the Markdown renderer and removed the offending styles. This should be fixed.
