### ISSUE TITLE
0 byte (0B) shown as size in tags

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/hub-beta-feedback#116]
![image](https://cloud.githubusercontent.com/assets/159209/8393245/80ff7266-1cbc-11e5-9dd0-5cc5ce9e4b36.png)

**Comment by ChristopherBiscardi** [comment]
This is a known issue with how we retrieved and stored the image sizes. We're working on a fix.

**Comment by ChristopherBiscardi** [comment]
This should be fixed. Please re-open if it is not
