### ISSUE TITLE
login page: UI highlights wrong button

### ISSUE THREAD

**Issue by pmario** [docker/hub-beta-feedback#118]
to reproduce: 

* go to: https://hub-beta.docker.com/
* top right there are 2 buttons:     [Sign up]   [Log In]
  * Sign up  ... is highlighted, but does nothing if you click it, because you are already on the sign up page

expected behaviour 
  * Log In ... should be highlighted, to show users, where to click, to enter the page for existing users.

**Comment by pmario** [comment]
hmm, closed without a comment and no fix? 

@nhsiehgit I took the time to create an issue, for something, that I think is broken on the landing page. You closed it without investing 1 minute, to tell me and the community, why it's a wontfix. 

Do you really want to get feedback?

**Comment by nhsiehgit** [comment]
@pmario Sorry, i got a PR in that closes this issue, and accidentally added the `closes: {said issue}` in the PR.

Don't worry, we heard your concern and it has been addressed :)

reopening & labeling as `pending-deploy` until prod released

**Comment by pmario** [comment]
OK. Thanks for the fast feedback :)

**Comment by ChristopherBiscardi** [comment]
The signup button is no longer highlighted on the signup page. We may in the future also choose to highlight the Login button in it's place. Thanks for the feedback @pmario 

<img width="1427" alt="screenshot 2015-08-04 10 50 24" src="https://cloud.githubusercontent.com/assets/551247/9068168/a6fb4a6a-3a96-11e5-9b7e-76035419c9c2.png">
