### ISSUE TITLE
Missing information about automated builds

### ISSUE THREAD

**Issue by djmaze** [docker/hub-beta-feedback#121]
The beta hub does not (yet?) show any information pertaining to automated builds. I am particularly missing the link to the connected source code repository. Is this planned?

**Comment by ChristopherBiscardi** [comment]
It is indeed planned. We will not ship [GA](https://github.com/docker/hub-beta-feedback/milestones) until functionality on Hub 2.0 is a superset of Hub 1.0.

**Comment by jakirkham** [comment]
Now seeing the source repo link. Glad to see it also works with private GitHub repos. :)

**Comment by rrarunan** [comment]
This issue is around beta, and we have added more information to the autobuilds pages since then.
