### ISSUE TITLE
Docker tags are undefined

### ISSUE THREAD

**Issue by luthur** [docker/hub-beta-feedback#122]
URL: `https://hub-beta.docker.com/_/mongo/`
![image](https://cloud.githubusercontent.com/assets/895300/8546189/2e1c1a84-24e8-11e5-9b2d-921d4221fde3.png)

**Comment by ChristopherBiscardi** [comment]
We have a fix for this. It's due to a change we made to the markdown rendering and should be fixed within the week as a part of larger changes.

**Comment by tianon** [comment]
Probably known, but I'd point out that it appears to affect _all_ `<a>` tags.

**Comment by tianon** [comment]
This appears to be fixed now. :+1:

**Comment by ChristopherBiscardi** [comment]
Closing as it has indeed been shipped.
