### ISSUE TITLE
HTML Title

### ISSUE THREAD

**Issue by TeckniX** [docker/hub-beta-feedback#125]
None of the pages have proper HTML titles - With multiple tabs open for Hubs, I find this very inconvenient:
`<title></title>`
vs current
`<title>Signup - Docker</title>`

**Comment by TeckniX** [comment]
Just saw within the list it's low-priority here:
https://github.com/docker/hub-beta-feedback/issues/124

**Comment by pkennedyr** [comment]
Page titles are now available on Docker Hub.
