### ISSUE TITLE
Incomplete Repositories Listing

### ISSUE THREAD

**Issue by wgerber** [docker/hub-beta-feedback#129]
On the Repositories listing page I only see the first 10 of my Repositories.  The pagination controls on the bottom only show 1 page.  I can't get to the rest of my Repositories.

**Comment by fakewaffle** [comment]
Same here.

**Comment by ChristopherBiscardi** [comment]
ping @rrarunan 

We have to show the "next" page as a number even if we don't have the full count from the API for `next+n` pages.

**Comment by wgerber** [comment]
That isn't quite the problem.  I can't actually get to the rest of the listing of my Repos.  I have more than 10 and I can't see the list for the rest.  The pagination at the bottom should allow me to go to the next page but does not.

**Comment by astopy** [comment]
I get the following in the JS console:

    client.bf3c492beac45c973cea.js:1 Download the React DevTools for a better development experience: https://fb.me/react-devtools
    client.bf3c492beac45c973cea.js:1 Warning: Failed propType: Required prop `prev` was not specified in `Pagination`. Check the render method of `UserProfile`.
    2client.bf3c492beac45c973cea.js:1 Uncaught Error: Invariant Violation: Missing "user" parameter for path "/r/:user/"

**Comment by rrarunan** [comment]
Related to #36. Closing since, pagination is fixed for the repos list. We are working on improving filtering of repos #198 .
