### ISSUE TITLE
Change 'Teams' to 'Organizations' in top menu

### ISSUE THREAD

**Issue by kizbitz** [docker/hub-beta-feedback#13]
1) Clicking *Teams* in the top menu actually takes you to a list of the organizations your account belongs to
2) The large *Organizations & Teams* header section should be removed or changed to just *Organizations* because at this point you're not looking at any teams.
![screen shot 2015-06-04 at 10 56 15 am](https://cloud.githubusercontent.com/assets/201920/7987092/54b2ffc2-0aa9-11e5-8536-e9cc46ee7551.png)

**Comment by ChristopherBiscardi** [comment]
Fixed in the recent deploy
