### ISSUE TITLE
Collaborators Page

### ISSUE THREAD

**Issue by wgerber** [docker/hub-beta-feedback#130]
When viewing a private repo I click on Settings and then Collaborators.  The content area of the screen gets the "Collaborators" heading line and nothing else.  Totally blank.  No way to view or edit the collaborators for this private repo.  I have tried this in the latest Firefox and Chrome.

**Comment by jakirkham** [comment]
+1

**Comment by jakirkham** [comment]
I think this has been fixed, no? I am able to view the collaborators. I can remove and add users.

**Comment by jakirkham** [comment]
@wgerber, can you try to see if this is still an issue for you? If not, can we close this out?

**Comment by wgerber** [comment]
Seems to be working now, thank you!
