### ISSUE TITLE
Dockerfile view not showing line breaks

### ISSUE THREAD

**Issue by fazy** [docker/hub-beta-feedback#137]
Dockerfile was created in Vim on Debian so I'm fairly sure the line breaks are normal `\n`.

`https://hub-beta.docker.com/r/<organisation>/<repository>/~/dockerfile/` shows everything on one line/paragraph.

**Comment by jakirkham** [comment]
Also, seeing this with all Dockerfiles. Color coding is not showing up either. Would add that fixed width font would be preferable when looking at code like this (as is done on the regular site).

**Comment by xdays** [comment]
+1

**Comment by Tzaphkiel** [comment]
Indeed, for me as well:
Line breaks missing
No syntax highlight.

**Comment by kencochrane** [comment]
Confirmed

![screenshot 2015-08-04 12 28 41](https://cloud.githubusercontent.com/assets/261601/9066245/766cde64-3aa4-11e5-92c5-c09cdbbad740.png)

**Comment by jakirkham** [comment]
So, this appears to be fixed.

**Comment by jakirkham** [comment]
Anybody still able to reproduce this error? @fazy @xdays @Tzaphkiel

**Comment by fazy** [comment]
Looks ok to me now. I get syntax highlighting too! Thanks. :)

**Comment by jakirkham** [comment]
I think this can be closed then.
