### ISSUE TITLE
Automated builds show "Last pushed: never" (why?)

### ISSUE THREAD

**Issue by jakirkham** [docker/hub-beta-feedback#140]
See example ( https://hub-beta.docker.com/r/jakirkham/ubuntu_conda/ ). It would be nice if this said something useful like "Last Built: ...".

**Comment by ChristopherBiscardi** [comment]
Ah, thanks for bringing this up. The confusion lies in that "pushed" refers to the image being pushed to the registry. This happens either manually (`docker push`) for a normal repo or by our Automated Build system for an Automated Repo.

**Comment by jakirkham** [comment]
Agreed, they are different methods, but you are corrected that they both push at the end.

**Comment by jakirkham** [comment]
It does look like this is being address. However, it appears that the times are off in some cases. See again the aforementioned repo ( https://hub-beta.docker.com/r/jakirkham/ubuntu_conda/ ) and the non-beta view of it here ( https://registry.hub.docker.com/u/jakirkham/ubuntu_conda/ ).

**Comment by rrarunan** [comment]
@jakirkham It does seem like the time is a bit more granular in the non-beta view, while the beta one is rounded off. We could get a bit more precise. We'll see what we can do there. Thanks!

**Comment by jakirkham** [comment]
Ok, sorry to be nitpicky, @rrarunan. I just wanted to know why this was happening.

**Comment by rrarunan** [comment]
@jakirkham :) no problem.

**Comment by jakirkham** [comment]
Thanks everyone. I'm considering this solved (rounding decisions aside).

**Comment by jakirkham** [comment]
Putting rounding issue here ( https://github.com/docker/hub-beta-feedback/issues/180 ).
