### ISSUE TITLE
Source project link shown on non-automated build repo.

### ISSUE THREAD

**Issue by kencochrane** [docker/hub-beta-feedback#147]
https://hub-beta.docker.com/r/kencochrane/busybox/ is a normal repo, if you go to the page, you will see a source project button. This button should not be there since it is a normal repo, and not an automated repo. When you click on the link it just goes to the same page.

<img width="1340" alt="screenshot 2015-08-03 16 25 03" src="https://cloud.githubusercontent.com/assets/261601/9046942/59366610-39fc-11e5-8c1b-90989b188a19.png">

**Comment by nhsiehgit** [comment]
No longer an issue. closing
