### ISSUE TITLE
Delete repo confirmation page is ugly

### ISSUE THREAD

**Issue by kencochrane** [docker/hub-beta-feedback#148]
The delete repo confirmation page is a little ugly, it could use some love.

We should also require more of a confirmation, maybe something like github does, where they require you type in a text box a string like "delete" or the repo name, before the delete button shows up, to let the person know what they are doing, and not accidentally deleting it, by clicking wrong button.

<img width="681" alt="screenshot 2015-08-03 16 27 22" src="https://cloud.githubusercontent.com/assets/261601/9046985/a8cec686-39fc-11e5-9693-d44bccbcfa13.png">

**Comment by nhsiehgit** [comment]
![screen shot 2015-08-06 at 1 53 39 pm](https://cloud.githubusercontent.com/assets/6186377/9123302/7d1d7778-3c43-11e5-81b2-daac1e29d7f2.png)

updated in latest deploy
