### ISSUE TITLE
Navgating between User/Organization repositories/settings is unintuitive

### ISSUE THREAD

**Issue by kizbitz** [docker/hub-beta-feedback#15]
Links/Pages for editing user account settings and organization account settings are not clearly separated. This leads to problems like a user signing up for private repositories on their user account instead of their organization account. The dropdown navigation on the left (username) is not intuitive. Current hub also has this problem: See: https://docker.atlassian.net/browse/ST-2045

1st Example: If my goal is to sign up for private repositories on an organization I would expect to:
1) Log in and be at the dashboard
2) Click a link to get to my organizations. Which is 'Teams' at the moment. See: https://github.com/docker/hub-beta-feedback/issues/13
3) Click on the organization that I want the private repositories on
4) Click the 'Billings and Plans' button
5) Proceed to sign up.

If I would follow the steps listed above I would end up subscribing under my personal account because there are User account links and Organization account links on the same page. In the screen shot below the secondary menu is all user account related, but the main section is settings about the organization.
![screen shot 2015-06-04 at 11 46 47 am](https://cloud.githubusercontent.com/assets/201920/7988089/9aed474e-0aaf-11e5-947f-b45a25b16f2f.png)

---

2nd Example: I want to view repositories on an organization that I belong to. I expect to:
1) Log in and be at the dashboard
2) Click a link to get to my organizations.
3) Click on the organization to view the repositories.

If I follow these steps I end up on the settings page for the repo (With other unrelated links as described above) - What I would think would be available is a dashboard page (with a list of repositories) for the organization (Same as the user account dashboard) - From there if I wanted to edit settings, billing, etc... for the org I could click the appropriate link.

The left hand drop down for selecting an org or the user account hasn't worked well in the current hub and I expect we'll see the same support tickets/problems if we continue to use it.

**Comment by ChristopherBiscardi** [comment]
Thanks for the feedback on this.

I mostly agree with you and we have some cycles being spent on "Orgs and Teams" flows which definitely leave something to be desired in their current state.

**Comment by ChristopherBiscardi** [comment]
We reformulated these pages and it was deployed in the most recent push. It will take a little bit to fill out some of the pages but the skeleton is up. If this is still an issue, please open a new issue directed at the new UI.
