### ISSUE TITLE
Trying to add a public repo gives wrong error message

### ISSUE THREAD

**Issue by kencochrane** [docker/hub-beta-feedback#150]
I tired to add a repo to a namespace I didn't have access too, I set it to public, but when I hit create, it says I didn't have any private repos available. The error should probably says you don't have permissions to add to that name space.

<img width="1314" alt="screenshot 2015-08-03 16 31 20" src="https://cloud.githubusercontent.com/assets/261601/9047057/2ee87866-39fd-11e5-8a92-bb02dca58ae2.png">

**Comment by nhsiehgit** [comment]
Namespaces should no longer present orgs you don't have permissions to.
