### ISSUE TITLE
Clicking Create Organization + button on create organization page submits form

### ISSUE THREAD

**Issue by kencochrane** [docker/hub-beta-feedback#151]
Not sure if this is by design or a bug, but I'll report anyway and you can close if by design.

I went to create an organization and on the create organization page, there are 2 buttons "create" at the bottom of the form and a "create organization +" button in the top right. If you click the button in the top right "create organization +" it submits the form, just like the create button.

Not sure why we need two buttons, maybe remove the one at the top?

<img width="1322" alt="screenshot 2015-08-03 16 34 52" src="https://cloud.githubusercontent.com/assets/261601/9047126/a93425d4-39fd-11e5-8883-2457c031a7db.png">

**Comment by rrarunan** [comment]
Yeah, the button on the top, seems redundant and is only redirecting the user to the same form again. Will remove.

**Comment by nhsiehgit** [comment]
remedied in latest deploy
![screen shot 2015-08-06 at 2 19 03 pm](https://cloud.githubusercontent.com/assets/6186377/9123701/20d856ec-3c46-11e5-92f7-8b2645516b88.png)
