### ISSUE TITLE
When not owner, trying to add team to org, gives wrong error message

### ISSUE THREAD

**Issue by kencochrane** [docker/hub-beta-feedback#156]
I tried to add a team to my org and it failed, the input is valid, and it doesn't already exist. 

<img width="1290" alt="screenshot 2015-08-03 16 54 01" src="https://cloud.githubusercontent.com/assets/261601/9047500/64ea272c-3a00-11e5-84fa-4286e04e6630.png">

**Comment by kencochrane** [comment]
OK, it looks like the error was because I wasn't an owner of that org, so the error message is wrong for creating a team.

**Comment by kencochrane** [comment]
If not an owner, we shouldn't show the create team option.

**Comment by rrarunan** [comment]
@kencochrane yes, we should not display the `create team` dialog when the current user is not an owner. Will remove.

**Comment by kencochrane** [comment]
@rrarunan should be the same with edit team as well, if don't have permissions, then don't show

**Comment by nhsiehgit** [comment]
updated in latest prod release
