### ISSUE TITLE
Floating "public" and "private" radio buttons

### ISSUE THREAD

**Issue by marcusmartins** [docker/hub-beta-feedback#159]
The "public" and "private" radio buttons on the organization page doesn't explain what they do. Does it control the default repository visibility?

![Image]
(https://www.dropbox.com/s/dux2oudstvfq931/Screenshot%202015-08-03%2016.40.50.png?dl=1)

**Comment by ChristopherBiscardi** [comment]
ping @nhsiehgit

**Comment by nhsiehgit** [comment]
handled in latest prod release
