### ISSUE TITLE
"Source Project" button opens the same page on a different tab

### ISSUE THREAD

**Issue by marcusmartins** [docker/hub-beta-feedback#160]
Steps to reproduce:
* Go to https://hub-beta.docker.com/_/ubuntu/
* Click on "Source Project" button

Result:
It opens a new tab with the same content.

Expected result:
?

**Comment by ChristopherBiscardi** [comment]
For Official Repos, I don't think we have access to the "Source Repo" since it should only be appearing on automated builds. Closing this in favor of #147

**Comment by ahmetalpbalkan** [comment]
@ChristopherBiscardi It doesn't work for automated build repos either. Reopening an issue at #288.
