### ISSUE TITLE
Profile picture blown out of proportion/resolution

### ISSUE THREAD

**Issue by Tzaphkiel** [docker/hub-beta-feedback#162]
When going to the profile page, the left-most picture is stretched to the size of the box it is in. If the picture's resolution is lesser than the size of the box, the image is stretched causing it to pixelate badly.

**Comment by rrarunan** [comment]
@Tzaphkiel Thanks for the report. We will look into this.

**Comment by ChristopherBiscardi** [comment]
@rrarunan Not sure there's much we can do about this other than suggest a higher-resolution image is uploaded. (interesting tidbit: This is one of the last remaining direct calls to gravatar).

@Tzaphkiel Please reopen if you have a proposal for a fix. Your profile photo features the same pixellation on GitHub, which means it is likely that the photo you are using is not at a high enough resolution for display at larger sizes.

![screenshot 2015-08-04 03 31 20](https://cloud.githubusercontent.com/assets/551247/9058866/753cc8b0-3a59-11e5-891a-8a2f85bc1edb.png)
