### ISSUE TITLE
Adding a repo from org page where not owner leaves namespace pull down blank

### ISSUE THREAD

**Issue by kencochrane** [docker/hub-beta-feedback#166]
I have a test user 'kentest' this user is part of an org 'kenco2', this user is not an owner.

When I click on the add repo link on the 'kenco2' org home page (https://hub-beta.docker.com/u/kenco2/dashboard/) , it takes me to this URL https://hub-beta.docker.com/add/repository/?namespace=kenco2

On that page, there is a form to add a new repo, but there are no values in the namespace pull down. Since I'm not an owner of this org, I'm not allowed to add repos, so that is fine, but it should at least show my normal namespace to allow me to add it there.

<img width="1313" alt="screenshot 2015-08-04 10 30 01" src="https://cloud.githubusercontent.com/assets/261601/9063104/f5518cfe-3a93-11e5-8bb2-450c69865a8b.png">

If I go to the add repo page (https://hub-beta.docker.com/add/repository/) without the ?namespace=kenco2 on the url, and it works fine, so it is something with the namespace filter that isn't working.

**Comment by nhsiehgit** [comment]
remedied with latest deploy! :)
