### ISSUE TITLE
click "my profile" link gives "TypeError: e is undefined" error

### ISSUE THREAD

**Issue by kencochrane** [docker/hub-beta-feedback#167]
When I click the "my profile" link in the nav pull down, it doesn't do anything, and when I look at the console it gives me an error. 

"TypeError: e is undefined"

<img width="1304" alt="screenshot 2015-08-04 10 54 47" src="https://cloud.githubusercontent.com/assets/261601/9063810/6468a6f6-3a97-11e5-9d92-fb097521fa4e.png">

**Comment by rrarunan** [comment]
reproduced in FF 39, windows 7.

**Comment by ChristopherBiscardi** [comment]
@rrarunan is this still an issue? I'm unable to reproduce.

**Comment by kencochrane** [comment]
Working for me now.

**Comment by kencochrane** [comment]
closing since it is now fixed.
