### ISSUE TITLE
Viewing automated build details caused browser login prompt

### ISSUE THREAD

**Issue by kencochrane** [docker/hub-beta-feedback#170]
When viewing the build details on one of automated builds, I was prompted with a login box

![screenshot 2015-08-04 12 08 52](https://cloud.githubusercontent.com/assets/261601/9065764/b64226f0-3aa1-11e5-96a1-0ef6f54e0cc3.png)

**Comment by kencochrane** [comment]
It looks like there is an error somewhere, and then I get logged off. which then causes the auth prompt, vs sending me to a login page.

**Comment by nhsiehgit** [comment]
ping @rrarunan ?

**Comment by ChristopherBiscardi** [comment]
This should be pending deploy.

**Comment by kencochrane** [comment]
Not seeing this anymore. Might have been fixed with recent deploy.

**Comment by ChristopherBiscardi** [comment]
Closing as a result
