### ISSUE TITLE
Going to build details page throws error

### ISSUE THREAD

**Issue by kencochrane** [docker/hub-beta-feedback#173]
I got this error when going to the build details page:

Uncaught Error: Invariant Violation: Missing "build_code" parameter for path "/r/:user/*/builds/:build_code/"

![screenshot 2015-08-04 12 51 45](https://cloud.githubusercontent.com/assets/261601/9066812/b0a82f5e-3aa7-11e5-995f-49b33f6f515f.png)

When I tried to reproduce I couldn't do it, I kept getting logged out.

If I am logged in and then click around to get to https://hub-beta.docker.com/r/kencochrane/test-repo-test/builds/ it works, but if I copy and paste in the browser. It will log me out, and give me a 404 page.

**Comment by jakirkham** [comment]
Tried to reproduce pasting and it resulted in script hanging the browser and had to stop it.

**Comment by ChristopherBiscardi** [comment]
The new url for hub is `hub.docker.com` as of last night and I am unable to reproduce this issue.

The two results I get are a `404` for repos I don't have access to and the correct page for repos I do have access to.

**Comment by btigit** [comment]
We have similar problems too.
In some automated repositories, I got an following error when click "Build Settings".

<img width="1440" alt="error" src="https://cloud.githubusercontent.com/assets/778316/9346183/c8cc5246-4654-11e5-9bda-31c3aa380277.png">

In my case, I could reproduce this issue and "Build Settings" never works well even if I logged out.

**Comment by nhsiehgit** [comment]
hi @btigit,

Would you be able to check and see if this is still an issue? we deployed changes to fix this so hopefully it is resolved now

**Comment by btigit** [comment]
hi @nhsiehgit 
LGTM! thanks!

**Comment by nhsiehgit** [comment]
Awesome! :)
