### ISSUE TITLE
webhook json example is missing curly bracket

### ISSUE THREAD

**Issue by kencochrane** [docker/hub-beta-feedback#175]
The webhook json example is missing the curly bracket at the beginning.

![screenshot 2015-08-04 13 12 03](https://cloud.githubusercontent.com/assets/261601/9067294/87f2da34-3aaa-11e5-80c2-607e9cb8d5c0.png)

**Comment by kencochrane** [comment]
PR submitted and merged, should be fixed in next push to prod

**Comment by nhsiehgit** [comment]
deployed to prod!
