### ISSUE TITLE
url redirects from old version to new

### ISSUE THREAD

**Issue by bestcodecomua** [docker/hub-beta-feedback#178]
Can`t find any documentation about future changes in link to dockerfile, docker image page etc.

Will you have a redirect in new hub version? For example:

old https://registry.hub.docker.com/u/jwilder/nginx-proxy/
new https://hub-beta.docker.com/r/jwilder/nginx-proxy/

or

old https://registry.hub.docker.com/u/jwilder/nginx-proxy/dockerfile/
new https://hub-beta.docker.com/r/jwilder/nginx-proxy/~/dockerfile/

**Comment by kencochrane** [comment]
@bestcodecomua yes there will be redirects from the old hub site to the new one.

> old https://registry.hub.docker.com/u/jwilder/nginx-proxy/
> new https://hub-beta.docker.com/r/jwilder/nginx-proxy/

Yes

> old https://registry.hub.docker.com/u/jwilder/nginx-proxy/dockerfile/
> new https://hub-beta.docker.com/r/jwilder/nginx-proxy/~/dockerfile/

Yes

but URL will be hub.docker.com not hub-beta.docker.com once the switch is made.

**Comment by bestcodecomua** [comment]
ok, thanks
