### ISSUE TITLE
Login form inputs cannot be auto-filled by 1Password

### ISSUE THREAD

**Issue by nilium** [docker/hub-beta-feedback#182]
Might affect other password stores, but it's slightly inconvenient. Definitely doesn't break the entire site, so there are other things to focus on, but I feel like it shouldn't be necessary to copy/paste a password into the login form.

- _OS:_ Mac OS X 10.11 beta (15A243d)
- _Browsers & versions:_ Affects at least Chrome 44 and Safari 9.0 (11601.1.43)
- _URL:_ https://hub-beta.docker.com/login/
- _Username:_ nilium

Maybe related to the form inputs not having identifying IDs/classes to signal that they're login fields?

**Comment by nhsiehgit** [comment]
related: https://github.com/docker/hub-beta-feedback/issues/93

On our radar! :)

**Comment by nilium** [comment]
Roger! Want me to close this since #93 seems to cover it pretty well already?

**Comment by nhsiehgit** [comment]
Nah thats fine. lastpass, 1pass, onelogin, etc. I'm not entirely familiar with how each differs, but may as well keep it open if a fix for one doesn't remedy the other.

Thanks for filing!

**Comment by nilium** [comment]
It appears to be working for 1Password now. Not sure if that's down to changes in the beta or if that's 1Password figuring out how to identify the form fields, but seems like this isn't an issue anymore.

I'll close this tomorrow morning-ish unless someone wants to leave it open, since I can't reproduce the behavior from earlier.

**Comment by nhsiehgit** [comment]
:+1: thanks!

**Comment by ineu** [comment]
It doesn't work with LastPass as of August 21
