### ISSUE TITLE
Github Private/Public Linking Issues

### ISSUE THREAD

**Issue by kizbitz** [docker/hub-beta-feedback#186]
I've revoked all Docker apps from Github and tried to recreate the link.
Select "Public and Private"
<img width="720" alt="screen shot 2015-08-07 at 5 09 48 am" src="https://cloud.githubusercontent.com/assets/201920/9132578/8ce5891e-3cc2-11e5-98e6-8e3c7fb55945.png">

On the Github side it results in "Public Data Only"
<img width="825" alt="screen shot 2015-08-07 at 5 06 20 am" src="https://cloud.githubusercontent.com/assets/201920/9132595/a50edf86-3cc2-11e5-835a-35247734ce9d.png">

After linking it displays "Read/Write access" on the hub side:
<img width="364" alt="screen shot 2015-08-07 at 5 11 41 am" src="https://cloud.githubusercontent.com/assets/201920/9132626/e076845c-3cc2-11e5-84ff-c8cb8c5b07b4.png">

But...
I only see my personal repositories, not any of my organizations.
<img width="1284" alt="screen shot 2015-08-07 at 5 13 09 am" src="https://cloud.githubusercontent.com/assets/201920/9132648/058136d4-3cc3-11e5-91f1-bbfebe0fb61f.png">

**Comment by miry** [comment]
Same problem.

**Comment by mavenugo** [comment]
am unable to link my Github account as well. But have a slightly different problem.
When I click on the “Link Github” and select the recommended “Public and Private” access, the page circles back without any activity. But it worked fine for bitbucket.

**Comment by ChristopherBiscardi** [comment]
The github auth scoping issue is pending a deploy which will go out over the next few hours.

@mavenugo I've experienced the same and seemed to need to delete the access from GitHub's side to re-link. I've created https://github.com/docker/hub-beta-feedback/issues/196 to track that issue (which is separate from the scoping issue)

**Comment by rrarunan** [comment]
This has been deployed. @kizbitz @mavenugo @miry Please verify and report any issues you find.

**Comment by kizbitz** [comment]
@rrarunan - LGTM

**Comment by ChristopherBiscardi** [comment]
I verified this fix as well, closing.
