### ISSUE TITLE
Cannot add team to new private repo

### ISSUE THREAD

**Issue by include** [docker/hub-beta-feedback#188]
Hi,

I've switched to beta and now I can't add teams to private repos. Only users.

This is messing with my feng shui :)

#help #thanks

**Comment by francois2metz** [comment]
I confirm this. :cactus:

**Comment by kencochrane** [comment]
@include @francois2metz can you contact us at support@docker.com with the organization and private repo names you are having issues with so we can dig deeper.

**Comment by kencochrane** [comment]
I was able to confirm, we are looking at this now.

**Comment by include** [comment]
@kencochrane email sent. thanks :+1:

**Comment by sbutalia** [comment]
Having the same issue. I can't give pull access to collaborators.

**Comment by joshskinner** [comment]
+1  this is sort of a blocker.

**Comment by posita** [comment]
Is there an ETA on this? This is an absolute showstopper for us. This is a direct quote from the hub.docker.com landing page:

> **Collaborate As A Team**
> Role-based access control for easy sharing.

As long as this bug exists, the above claim is false. Sure, you can create teams and add users via <https://hub.docker.com/u/[ORGNAME]/dashboard/teams/devs/>, but then what? There is no longer any way to associate a team with a role in a repository, public or private, only users, and even that's broken in more ways than one (see #197 [you can only add read users, which is useless because readers can't push]; #214 [no feedback for non-existent users, e.g., if you mistype].).

**Comment by rrarunan** [comment]
@posita This particular bug was fixed with last push on Friday. Please verify if you can add permissions now on already existing teams. Adding a new team to the collaborators #188 (which is related, but not the same), we will provide an update on Monday.

**Comment by christoph-hipp** [comment]
We also see this as blocker. Do you have an idea when there will be a fix?

We converted the private account to an organization last week. 
This worked well, including user groups (teams) and authorizations.

As of today we are unable to push images with any of the users,
regardless if the authorization has been specified via a team, or for
the individual users. Users in the 'owners' team are unable to change
authorizations, etc.

The UI only seems to allow individual users to be added as
collaborators, the team functionality seems dead.

It also seemed impossible (yesterday) that the new UI supports deleting of individual tags (what was possible with the old UI).

Thanks for any update on this.

**Comment by tobowers** [comment]
I have the same problem. I filled out the web support UI and was directed here. Doesn't look like there are workarounds?

**Comment by kencochrane** [comment]
Current ETA for this fix is today, we are currently testing, once we confirm it is fixed, we will push to prod and update this ticket.

**Comment by christoph-hipp** [comment]
@kencochrane Right now nothing is working on Hub. I cant even open the Collaborator setting nor delete a repository. Since we did not gent an update from you, I guess that the issues on your side are pretty serious. Do you meanwhile have an updated ETA?

**Comment by kencochrane** [comment]
Sorry, we ran into issues during testing, and we need to fix those first before we can push to prod.

@christoph-hipp if you shift reload the page, does it still not work? If so, can you check your browser console to see if there are any JavaScript errors?

**Comment by francois2metz** [comment]
Now the collaborators page is not loaded or trigger a 502 Bad Gateway when loaded directly.

Console results when clicking on the collaborators menu entry:
```
Warning: Failed propType: Required prop `count` was not specified in `t`. Check the render method of `t`. client.78f7642e1d6b566ac84b.js:1:15690
Warning: Failed propType: Required prop `results` was not specified in `t`. Check the render method of `t`. client.78f7642e1d6b566ac84b.js:1:15690
TypeError: e.props.results is undefined
```

And I get 2 400:

- https://hub.docker.com/v2/repositories/xxx/xxx/collaborators/: Org repositories do not have collaborators. Use the `groups` url.
- https://hub.docker.com/v2/repositories/xxx/xxx/groups/: User repositories do not have groups. Use the `collaboroators` url. (typo in not mine)

**Comment by christoph-hipp** [comment]
@kencochrane No, it still does not work. It is completely broken...

<img width="336" alt="https___hub_docker_com_r_softpro_signdoc-develop___settings_collaborators_" src="https://cloud.githubusercontent.com/assets/2820785/9193627/22eb2aa4-4015-11e5-8bc8-452311a3c36e.png">

**Comment by kencochrane** [comment]
Thanks for the info.

/cc @ChristopherBiscardi

**Comment by kencochrane** [comment]
Are you just getting the 502 on that one page, or all over?

**Comment by francois2metz** [comment]
It happens only on my repo with no teams associated and under my organization.

**Comment by kencochrane** [comment]
@francois2metz can you email me at ken@docker.com with your username and repo name and I'll investigate further.

@christoph-hipp same with you, can you put your username here, or email me, so I can dig deeper?

**Comment by christoph-hipp** [comment]
@kencochrane Looks like it limited to the collaborators page. Is it any different for you?

**Comment by kencochrane** [comment]
@christoph-hipp I was able to reproduce on one of my orgs, but not another one. trying to find cause now.

**Comment by kencochrane** [comment]
@christoph-hipp @francois2metz replied to your emails, let me know how that works for you

**Comment by kencochrane** [comment]
@posita if you are still having issues, please let me know, I believe I have a work around until the fix goes to prod, which should hopefully be very soon.

**Comment by christoph-hipp** [comment]
@kencochrane Looks like it is working now. Thank you.

**Comment by kencochrane** [comment]
@christoph-hipp you're welcome, I'm sorry for all of the trouble.

**Comment by francois2metz** [comment]
Seems fixed on my side \o/

**Comment by posita** [comment]
@kencochrane, the interface appears to work. I'm going to see whether it actually affects pushing/pulling.

**Comment by kencochrane** [comment]
@posita how did your testing go?

**Comment by posita** [comment]
This looks like it's working for my use cases, although I have not done exhaustive testing to ensure enforcement (e.g., can't push from account with read-only access, etc.).

**Comment by kencochrane** [comment]
@posita ok, thank you for confirming.

**Comment by remitaffin** [comment]
@kencochrane: I'm having a 502 on collaborator page too.
I created a new private repo and I can't update the collaborators on this repo:
<img width="646" alt="screen shot 2015-08-11 at 2 31 00 pm" src="https://cloud.githubusercontent.com/assets/9221626/9206804/f6a6ef1e-4037-11e5-8ebd-ae5523247b14.png">

Thanks.

**Comment by kencochrane** [comment]
@remitaffin try it now. Sorry the fix is a manual one until we push the permanent fix.

**Comment by remitaffin** [comment]
Yeah, this is fixed now.
Thanks @kencochrane!

**Comment by dnegstad** [comment]
@kencochrane Same issue for a new repo on our org account:
https://hub.docker.com/r/pk4media/xps.identity/~/settings/collaborators/

Thanks for taking a look.

**Comment by kencochrane** [comment]
@dnegstad try it again

**Comment by hirokiky** [comment]
I got same one, good luck :+1:

**Comment by kencochrane** [comment]
@hirokiky should be fixed, try again.

**Comment by hirokiky** [comment]
@kencochrane awesome! there's no problem. Thank you.

**Comment by kencochrane** [comment]
The permanent fix should be pushed to prod at this point, so this issue should be resolved, if you are still seeing issues, please email support@docker.com because it might be related to something else.

**Comment by kencochrane** [comment]
@hirokiky good news, you're welcome

**Comment by dnegstad** [comment]
@kencochrane Thanks for the fix, it's working great!

**Comment by include** [comment]
:+1:

**Comment by nicolasunravel** [comment]
I'm experiencing the same since a few days, please re open

**Comment by rplute** [comment]
Experiencing this same issue as well. Definitely blocking us.

**Comment by kencochrane** [comment]
ping @marcusmartins @akshayvyas

**Comment by lucas-a-rodrigues** [comment]
Please reopen! This issue is blocking my team too...

**Comment by kencochrane** [comment]
@lucas-a-rodrigues @rplute @nicolasunravel I have been told the issue has been fixed. If you can confirm, that would be great.

**Comment by rplute** [comment]
@kencochrane, I can confirm on my end! Thanks!

**Comment by nicolasunravel** [comment]
yes, works now. thanks

**Comment by lucas-a-rodrigues** [comment]
Thanks!!! You're great!!!

**Comment by joeygeo** [comment]
9 years later, I am stuck with this issue!
