### ISSUE TITLE
Add ability to delete repositories

### ISSUE THREAD

**Issue by kizbitz** [docker/hub-beta-feedback#19]
Currently can't delete repositories.

**Comment by wallnerryan** [comment]
:+1:

**Comment by n0mer** [comment]
just in case - the workaround is to use hub.docker.com and remove repo there

**Comment by nathanleclaire** [comment]
A _very serious_ +1 to this issue - if a user accidentally pushes an image which contain secrets or sensitive information, it's critical that they should be able to delete the repo.  I know, _"You should treat the secrets as completely compromised and rotate the keys if this happens"_.  That's not going to help in the situation where the user pushes an image containing secret source code that they now get to flail around helplessly leaking to the entire world.

**Comment by rrarunan** [comment]
deployed.

**Comment by oleksdovz** [comment]
I can not delete own repo. I see windows delete  or cancel and I clicking delete but no results or progress
Repo in hub odovzhan/centos-was-ready
