### ISSUE TITLE
Blue background on avatar in the dashboard

### ISSUE THREAD

**Issue by francois2metz** [docker/hub-beta-feedback#192]
There is a blue background on avatar in the dasboard when the avatar is transparent.

![blue-background](https://cloud.githubusercontent.com/assets/86659/9138721/d7c27092-3d25-11e5-805a-ca9275ee67d8.png)

![no-background](https://cloud.githubusercontent.com/assets/86659/9138722/d7d844da-3d25-11e5-9a95-17eb4fda9a8c.png)

I prefer without the blue background.

**Comment by ChristopherBiscardi** [comment]
This is in-progress. The second example is what we'll be going with.

**Comment by ruffsl** [comment]
+1

**Comment by nhsiehgit** [comment]
Should be fixed now!
closing

**Comment by ruffsl** [comment]
Thanks @nhsiehgit !

**Comment by ruffsl** [comment]
Oh, one suggestion these avatars to make the profile pages even cleaner, would be to remove the thin grey border around it. That is if you keep the transparency to the page's background color:
![image](https://cloud.githubusercontent.com/assets/2293573/9206764/99826dc2-401e-11e5-99e4-254aeda5da89.png)
https://hub.docker.com/u/osrf/
