### ISSUE TITLE
Unable to grant write access to collaborators

### ISSUE THREAD

**Issue by fazy** [docker/hub-beta-feedback#197]
For my organisation I have two teams, "owners" and "systems". The systems team now has "read" access to a private repository, and I want to change this to "write". I am in the "Owners" team, with "Admin" access.

Steps taken:

* Go to a private repository and click "Collaborators" (https://hub.docker.com/r/ORG/REPO/~/settings/collaborators/)
* Click "remove" next to the "systems" team (where it currently shows "read" access (team is successfully removed)
* On the right, select "systems" and "Write" from the drop-downs and click "Add Team"

Expected:

Team appears in the list with "Write" access.

Actual:

Team appears in the list but only with "Read" access.

I also tried adding write access while the team was already there with read access. This gave no discernible response from the UI.

**Comment by kencochrane** [comment]
related to https://github.com/docker/hub-beta-feedback/issues/188

**Comment by posita** [comment]
ETA? Not being able to add users with push access is a showstopper for organizations.

**Comment by posita** [comment]
ETA? Not being able to add users with push access is a showstopper for organizations. By the way, I'm not seeing *any* team-related interface in `.../settings/collaborators/` (see #188). The only functionality I see is for users.

**Comment by rrarunan** [comment]
@posita This particular bug was fixed with last push on Friday. Please verify if you can add permissions now on already existing teams. Adding a new team to the collaborators #188 (which is related, but not the same), we will provide an update on Monday.

**Comment by posita** [comment]
> Please verify if you can add permissions now on already existing teams.

Do you mean teams that are already associated with the repository? I have no repositories left that have teams associated with them after falling victim to this FUBAR, so until #188 is fixed, I can't do anything with this.

**Comment by rrarunan** [comment]
#188 is closed now and, this should be fixed now. Closing, until someone reopens with an issue regarding this.
