### ISSUE TITLE
Git repo list is unwieldy in Automated Build Creation

### ISSUE THREAD

**Issue by huslage** [docker/hub-beta-feedback#2]
Finding the repo I want to use in this list is maddening:

https://www.dropbox.com/s/8m7mz0dhrylskhk/Screenshot%202015-06-03%2019.07.22.png?dl=0

**Comment by ChristopherBiscardi** [comment]
Copying image to inline.

![image](https://cloud.githubusercontent.com/assets/551247/7973921/47fa5b20-0a10-11e5-8546-05cb3edc345a.png)

**Comment by mchiang0610** [comment]
:+1: I had to look a while for the test repo.

**Comment by rrarunan** [comment]
@jsouth ^^ we need to sit down for this.

**Comment by ChristopherBiscardi** [comment]
@huslage @mchiang0610 Would it help if this list were easily filterable?

@rrarunan The proposed functionality would end up being similar to GitHub's "repo filter" functionality, which should be fine since we have the entire list of repos here.

![screenshot 2015-06-04 06 53 08](https://cloud.githubusercontent.com/assets/551247/7985551/63053a4a-0a86-11e5-91ab-216baed791df.png)

**Comment by huslage** [comment]
This would be perfect

On Thu, Jun 4, 2015 at 9:54 AM, Christopher Biscardi <
notifications@github.com> wrote:

> @huslage <https://github.com/huslage> @mchiang0610
> <https://github.com/mchiang0610> Would it help if this list were easily
> filterable?
>
> @rrarunan <https://github.com/rrarunan> The proposed functionality would
> end up being similar to GitHub's "repo filter" functionality, which should
> be fine since we have the entire list of repos here.
>
> [image: screenshot 2015-06-04 06 53 08]
> <https://cloud.githubusercontent.com/assets/551247/7985551/63053a4a-0a86-11e5-91ab-216baed791df.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/hub-beta-feedback/issues/2#issuecomment-108906738>
> .
>



-- 
Aaron Huslage
Solution Architect - Docker, Inc.
+1-919-600-1712

**Comment by jsouth** [comment]
+1

**Comment by rrarunan** [comment]
I have updated the designs and workflow now. Please report back, if you still find any issues.
