### ISSUE TITLE
Add spacing on 'x' when deleting team members

### ISSUE THREAD

**Issue by kizbitz** [docker/hub-beta-feedback#20]
Need spacing between username and 'x' on the team members page
![screen shot 2015-06-04 at 2 52 48 pm](https://cloud.githubusercontent.com/assets/201920/7991905/9c231638-0ac9-11e5-895b-314ef372cbf6.png)

**Comment by ChristopherBiscardi** [comment]
This page is likely to undergo significant changes. Coming up with a better way to remove a member will be part of that.

**Comment by ChristopherBiscardi** [comment]
This is no longer an issue as the page no longer exists as shown in the screenshot on this ticket. The new teams item has a clearly marked `x`:

![screenshot 2015-06-13 11 27 32](https://cloud.githubusercontent.com/assets/551247/8145509/3a2ec6b4-11bf-11e5-85d4-7a85eca8de23.png)
