### ISSUE TITLE
Unable to setup automated build

### ISSUE THREAD

**Issue by ankushagarwal** [docker/hub-beta-feedback#206]
Tried to setup and Automated build, but got a 403 Forbidden when I clicked Create

![image](https://cloud.githubusercontent.com/assets/796949/9146196/70ef7aa6-3d0f-11e5-8405-c32da21fe7ef.png)

![image](https://cloud.githubusercontent.com/assets/796949/9146203/8492d134-3d0f-11e5-9d54-9c9e6e6048c0.png)

**Comment by rrarunan** [comment]
@ankushagarwal Can you confirm if this is a bitbucket or github repo. And, another question, have you connected to both github and bitbucket?

**Comment by ankushagarwal** [comment]
It's a github repo. I have connected both Github and Bitbucket.

**Comment by rrarunan** [comment]
@ankushagarwal A fix is on the way. Thanks for reporting!

**Comment by rrarunan** [comment]
@ankushagarwal Please verify if you can do so now. Thanks! Deployed this fix.

**Comment by ankushagarwal** [comment]
Thanks! It works now.

**Comment by rrarunan** [comment]
Ok, closing.

**Comment by stupied4ever** [comment]
I have the exact same problem just right now. Some idea about when it will be deployed?

**Comment by sjoeboo** [comment]
+1 , same issue.

**Comment by franky-continu** [comment]
+1
