### ISSUE TITLE
Browser prompts for password after clicking public repo

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/hub-beta-feedback#208]
?

![image](https://cloud.githubusercontent.com/assets/159209/9146381/22dd4012-3d11-11e5-90e9-513ca99f2c2c.png)

**Comment by mbentley** [comment]
This just happened to me when attempting to view https://hub.docker.com/r/mbentley/ubuntu-django-uwsgi-nginx/builds/bxkr8jkvcgtrb2utsknu2an/ one iPhone. I'm not currently logged in to the hub one phone if that helps.

**Comment by PaulAnnekov** [comment]
The same for me. Open this page https://hub.docker.com/search/?q=owncloud&page=1&isAutomated=0&isOfficial=0&starCount=0&pullCount=0 and click on l3iggs/owncloud link. You will see the same modal.

**Comment by ChristopherBiscardi** [comment]
This should be fixed in prod
