### ISSUE TITLE
Restore option to go back to unbroken UI (i.e., turn off beta)

### ISSUE THREAD

**Issue by posita** [docker/hub-beta-feedback#211]
I don't know if this is intentional, but I can no longer turn off the beta UI and go back to the production UI. There are large number of issues with the existing UI that prevent real work from being done (see, e.g., #188). It's not obvious how to return to the version of the UI that actually works.

**Comment by kunickiaj** [comment]
August 6 the "beta" UI became the new "prod" UI. Its still as unusable as the beta.

**Comment by posita** [comment]
Given all of the showstopping issues the new UI has, it is quite urgent to be able to restore the ability to revert to the working one.

**Comment by tobowers** [comment]
:+1: on this... seems like a lot is broken.

**Comment by ChristopherBiscardi** [comment]
Please file issues here if you run into bugs. @posita I know you have filed some already, thank you.
We are working on fixing the bugs in this tracker

The old site has been shut down following the beta period and is not going to come back at this time.

**Comment by posita** [comment]
@ChristopherBiscardi, understood and thanks!
