### ISSUE TITLE
Cannot access settings page for my image

### ISSUE THREAD

**Issue by timlinux** [docker/hub-beta-feedback#217]
Hi

I'm trying to access the settings page for 

https://hub.docker.com/r/kartoza/postgis/~/settings/automated-builds/

as at 9 Aug 2015 and the page never loads.

**Comment by jwilder** [comment]
I have the same issue: https://hub.docker.com/r/jwilder/nginx-proxy/~/settings/automated-builds/.  I'm getting a 502 response.

**Comment by timlinux** [comment]
Some further info for clarification:

I have this same issue with other repos. I tested deleting and recreating one of my automated build based repos and the problem goes away - so it appears to be an issues with 'legacy' repos created before the shift to the new hub rollout.

Deleting and recreating repos, while is workaround is obviously a suboptimal fix since the repo will be offline while you do it, breaking others compositions. Also the stats get lost which is a pain...

**Comment by rrarunan** [comment]
Looks similar to #236. Looking into both.

**Comment by timlinux** [comment]
Thanks @rrarunan

**Comment by nhsiehgit** [comment]
Should be fixed now!
closing

**Comment by timlinux** [comment]
Yay - it loads now - thanks!
