### ISSUE TITLE
Automated build fails , but passes locally

### ISSUE THREAD

**Issue by meirwah** [docker/hub-beta-feedback#223]
In my meirwah/st2expresscloudslang repo (https://hub.docker.com/r/meirwah/st2cloudslang/builds/btejwoq8qsydyggmkbkfvbn/ )

my automate build fails on : 

Setting up postgresql (9.3+154ubuntu1) ...
Setting up postgresql-contrib-9.3 (9.3.9-0ubuntu0.14.04) ...
Setting up postgresql-contrib (9.3+154ubuntu1) ...
Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
[91mErrors were encountered while processing:
 mongodb-server
[0m
[91m mongodb
[0m
[91mE[0m
[91m: [0m
[91mSub-process /usr/bin/dpkg returned an error code (1)[0m

but works fine when I build it locally on my machine... any idea?

**Comment by thaJeztah** [comment]
I think this issue should be reported via https://support.docker.com (it's not related to the new web-interface)

**Comment by meirwah** [comment]
done (https://support.docker.com/hc/en-us/requests/6089) closing this...

**Comment by thaJeztah** [comment]
Thanks @meirwah hope you find a solution!
