### ISSUE TITLE
Bloated pages

### ISSUE THREAD

**Issue by KodeStar** [docker/hub-beta-feedback#228]
Take a look at this for example:

https://hub.docker.com/r/linuxserver/baseimage/~/dockerfile/

That page comes in at an impressive 1.8MB...

**Comment by dickensian** [comment]
404 on that link.

**Comment by KodeStar** [comment]
Works for me?  Here is a screenshot: https://drive.google.com/file/d/0B3_oyaclxtK0eUFnamhWSkZWOVE/view?usp=drivesdk

The point is there is basically nothing on the page, it shouldn't be coming in at 1.8MB

**Comment by ChristopherBiscardi** [comment]
We are planning on doing a few optimizations in the near future (code splitting, etc) which will help this. I'm going to close this issue in favor of more specific issues such as https://github.com/docker/hub-beta-feedback/issues/244
