### ISSUE TITLE
Short Description is not saved when setting up an Automated Build

### ISSUE THREAD

**Issue by kizbitz** [docker/hub-beta-feedback#23]
Set a short description when setting up an automated build:
![screen shot 2015-06-04 at 3 08 31 pm](https://cloud.githubusercontent.com/assets/201920/7992204/c64944d0-0acb-11e5-9b28-b61d9303c09a.png)

After saving the description is empty:
![screen shot 2015-06-04 at 3 08 58 pm](https://cloud.githubusercontent.com/assets/201920/7992206/d433833a-0acb-11e5-8d36-005aee7ba38d.png)

**Comment by ChristopherBiscardi** [comment]
@rrarunan This still looks like it's an issue after the deploy.

**Comment by rrarunan** [comment]
Did, @fxdgear's change get merged to prod. I don't think so yet.. I will keep the `pending-deploy` until we confirm that. `https://hub-beta-stage.docker.com/` works on stage.

**Comment by ChristopherBiscardi** [comment]
This seems to be working now. Closing
