### ISSUE TITLE
"Linked Repos" in the context of an Automated Build is ambiguous

### ISSUE THREAD

**Issue by ChristopherBiscardi** [docker/hub-beta-feedback#230]
Surfaced in https://github.com/docker/hub-beta-feedback/issues/209#issuecomment-128844471

![](https://cloud.githubusercontent.com/assets/2975811/9147324/404e6456-3d1a-11e5-869a-50343d495474.png)

The text should read "Linked Hub Repos" because it is conceivable that we could be referring to GitHub repos in this context.

Additionally, the text in the left hand side description should start as:

> Link your Automated Build to a Hub Repository...

I also wonder if we can't get more specific with the verbiage. Right now the wording says that a build is triggered when the other repo is "updated", but maybe it should say "pushed"?

**Comment by nhsiehgit** [comment]
@ChristopherBiscardi would Hub be still too ambigious? maybe DockerHub?
