### ISSUE TITLE
Hub login reports missing username / password when filled in by iCloud keychain

### ISSUE THREAD

**Issue by double16** [docker/hub-beta-feedback#231]
Steps to reproduce:
1. Login with Safari on OS X 10.x and allow password to be saved in keychain
2. Logout
3. Go to login page again and Safari should fill in username and password
4. Click button to login
5. Form reports username and password are required

If I click the mouse in the populated fields, it doesn't help. I need to add a delete a character in each field for it to accept.

**Comment by nhsiehgit** [comment]
relates to https://github.com/docker/hub-beta-feedback/issues/189

updating 189 to reflect all autofill issues and closing this ticket
