### ISSUE TITLE
Free private repository listed for Orgs

### ISSUE THREAD

**Issue by kizbitz** [docker/hub-beta-feedback#235]
Shouldn't have a free repository listed on the private repos:

Billing page (With 1 listed)

<img width="1322" alt="screen shot 2015-08-10 at 12 11 06 pm" src="https://cloud.githubusercontent.com/assets/201920/9176448/617e71fc-3f59-11e5-9e87-d9d68273186c.png">

Repository page (Indicator on top right)
<img width="1367" alt="screen shot 2015-08-10 at 12 12 33 pm" src="https://cloud.githubusercontent.com/assets/201920/9176454/67406906-3f59-11e5-8779-50270e887988.png">

**Comment by fauzanariffin** [comment]
The **"private"** option is still visible under the **Organization > Create Repo** page.

![image](https://cloud.githubusercontent.com/assets/7702461/9317770/9f9d4cb2-44f2-11e5-9265-18acb5b4e216.png)
