### ISSUE TITLE
Build Settings tab returns 502 Bad Gateway

### ISSUE THREAD

**Issue by siomiz** [docker/hub-beta-feedback#236]
Environment: Ubuntu 15.04, Firefox 39.0.3, ~12:16p, Aug 10th, 2015

It looks like I managed to break the automated build settings page of one of my repos, probably by repeatedly saving the Dockerfile locations for different tags (I would really appreciate some feedback on the "Save" button there, btw...);
https://hub.docker.com/r/siomiz/node-opencv/

when I click on the Build Settings tab I get the following Javascript error:

![screenshot from 2015-08-10 12 16 37](https://cloud.githubusercontent.com/assets/7343789/9181459/074aee4e-3f5a-11e5-83da-24f2a5fe7022.jpg)

when I open the URL of Build Settings directly I get:

![screenshot from 2015-08-10 12 17 38](https://cloud.githubusercontent.com/assets/7343789/9181558/70c0126e-3f5a-11e5-8d6e-d9fdffe9cf79.jpg)

**Comment by bfirsh** [comment]
https://twitter.com/AshBerlin/status/629617445708431360

Also, the page doesn't update on error but the URL does.

**Comment by cptactionhank** [comment]
When is the next deployment @nhsiehgit ?

**Comment by nhsiehgit** [comment]
@cptactionhank we've deployed to staging last night and are planning to move to prod sometime this morning. Thanks for your patience!

**Comment by cptactionhank** [comment]
Thanks, I really need to add more tags to some of my repositories

**Comment by nhsiehgit** [comment]
@cptactionhank Prod has been deployed. sorry for the delay!

would you be able to check if you can now access your build settings page? thanks

**Comment by cptactionhank** [comment]
Looks like it's working, waiting for it to finish building. Thanks!

**Comment by siomiz** [comment]
:smile: Thank you for the quick fix! (and sorry for the duplicate issue)
