### ISSUE TITLE
'Docker Pull' Textbox needs populated

### ISSUE THREAD

**Issue by kizbitz** [docker/hub-beta-feedback#24]
Populate the textbox with `docker pull <repo>`

![screen shot 2015-06-04 at 3 16 22 pm](https://cloud.githubusercontent.com/assets/201920/7992373/da3b35b0-0acc-11e5-9e4e-32d754bcbbe5.png)

**Comment by ChristopherBiscardi** [comment]
@kizbitz Can you give any more information as to how it got to this state? (What were you doing at the time, do you know of an easy repro, etc)

**Comment by kizbitz** [comment]
Looks like it might be a Firefox problem: 38.0.5 - All my repositories are empty like this.
Chrome is fine.

**Comment by ChristopherBiscardi** [comment]
ok. This is likely related to a superagent bug we've been running into. Thanks for the additional info.

**Comment by rrarunan** [comment]
Confirmed that problem exists in IE 11 as well.

**Comment by ChristopherBiscardi** [comment]
This looks fixed to me. Closing.
