### ISSUE TITLE
Pagination navbar is not intuitive

### ISSUE THREAD

**Issue by albertinisg** [docker/hub-beta-feedback#240]
Everytime I open my dashboard, the pagination navbar just displays `1` even if I have more than 1 page there. That makes me think that my other docker images are not available there.

However is not a bug, the pagination component should be redesigned as it is a bit confusing right now.

**Comment by dickensian** [comment]
Agreed, pagination needs to show the total number of pages or at the very least have some way of indicating that there are more pages in a given direction.

**Comment by francois2metz** [comment]
Almost duplicate of #36.

**Comment by nhsiehgit** [comment]
Thanks all, we have a fix in pending deploy!

**Comment by rrarunan** [comment]
We have updated the pagination component. @albertinisg @dickensian @francois2metz Let us know what you think.

**Comment by francois2metz** [comment]
Woooooot. Awesome. :tada:

**Comment by rrarunan** [comment]
Closing.

**Comment by albertinisg** [comment]
Looks exactly how I was thinking @rrarunan :smile:  Thanks for the quick fix!

**Comment by rrarunan** [comment]
@albertinisg thanks to @ChristopherBiscardi too. Thanks for the report.
