### ISSUE TITLE
Build vm runs out of space

### ISSUE THREAD

**Issue by timlinux** [docker/hub-beta-feedback#241]
When my image build is triggered, it is failing because the build env is running out of space:

```
Mktemp failed: mkdir /var/lib/docker/graph/_tmp/b221afe15218f5ba95c70760b0197a290d9d5c92bd5fdf03e7bca07193cb6e04: no space left on device
```

See https://hub.docker.com/r/kartoza/postgis/builds/bbazbopkpzeuyaa72xyc3ym/ for more details.

**Comment by ChristopherBiscardi** [comment]
The Automated Build limits are currently:

* 2 hours maximum build time
* 2 GB RAM
* 1 CPU
* 30 GB Disk Space

Please contact support support@docker.com if this issue persists.

**Comment by glenn-jocher** [comment]
We are using autobuild with the YOLOv5 repo https://github.com/ultralytics/yolov5 on a paid plan and keep getting this error message.
https://hub.docker.com/r/ultralytics/yolov5

<img width="1764" alt="Screenshot 2022-02-17 at 14 42 55" src="https://user-images.githubusercontent.com/26833433/154494152-2e550555-a42b-4dc4-a701-392ea14360c5.png">
