### ISSUE TITLE
Repos under organization not showing up

### ISSUE THREAD

**Issue by Neil-Ni** [docker/hub-beta-feedback#246]
I can see my organization, and I can also see my repos. But when I clicked under my organization, it's not showing me anything.

Console is showing:
{"detail": "DockerUser not of correct type.", "error": true}

<img width="1419" alt="screen shot 2015-08-11 at 5 58 42 pm" src="https://cloud.githubusercontent.com/assets/746239/9211873/d2799aa4-4052-11e5-8bcd-53b5588f368f.png">

**Comment by Neil-Ni** [comment]
It was working fine earlier this morning.

**Comment by ChristopherBiscardi** [comment]
@Neil-Ni Did you recently convert your Organization from a User?

**Comment by Neil-Ni** [comment]
nope

**Comment by Neil-Ni** [comment]
@ChristopherBiscardi seems to be fixed now. closing
