### ISSUE TITLE
No confirmation on making changes to build settings

### ISSUE THREAD

**Issue by timlinux** [docker/hub-beta-feedback#249]
As a follow on from #245, build settings now works nicely, but pressing SAVE gives no visual confirmation that the save actually succeeded. It would be great to notify the user when the SAVE has been completed otherwise we are left in doubt if the operation succeeded or not.

<img width="976" alt="screen shot 2015-08-12 at 08 10 22" src="https://cloud.githubusercontent.com/assets/178003/9217597/fdada93c-40c9-11e5-9737-dea49848c8b8.png">

**Comment by nhsiehgit** [comment]
closing. This should be resolved now.

Thanks for the ticket!

**Comment by timlinux** [comment]
Thanks for the fix!

Regards

Tim
