### ISSUE TITLE
build failed: wget Name or service not known

### ISSUE THREAD

**Issue by sinkcup** [docker/hub-beta-feedback#252]
on local PC : docker build success
on hub.docker.com : docker build failed

link:

https://hub.docker.com/r/openwrtio/openwrt-sdk-gee-ralink/builds/bkd5mhaabcqwukjenqgpar8/

error:

```
Step 5 : RUN wget http://downloads.openwrt.io/vendors/gee/ralink/hc5761-20140619.tar.gz
Resolving downloads.openwrt.io (downloads.openwrt.io)... 
failed: Name or service not known.
wget: unable to resolve host address 'downloads.openwrt.io'
```

**Comment by ChristopherBiscardi** [comment]
Please send an email to support@docker.com, who will follow up on this with you.
