### ISSUE TITLE
500 at listing repositories

### ISSUE THREAD

**Issue by eviltnan** [docker/hub-beta-feedback#253]
https://hub.docker.com/u/tbeu/dashboard/

![image](https://cloud.githubusercontent.com/assets/3502492/9223168/06fbe0b6-40f8-11e5-917a-c8c5f3a4ec39.png)

**Comment by ChristopherBiscardi** [comment]
@eviltnan Is this a recurring issue or was it ephemeral? I've successfully hit the endpoint in the screenshot without issue.

**Comment by eviltnan** [comment]
Can't repeat it now also, time to close the issue.

**Comment by ChristopherBiscardi** [comment]
Ok, I'll close now. Feel free to reopen if this pops up again.
