### ISSUE TITLE
Remove 'official' word in each item of repository list

### ISSUE THREAD

**Issue by marcosalberto** [docker/hub-beta-feedback#254]
Is necessary the word "official" in each item the [list of repositories](https://hub.docker.com/explore/)?
I think that the priority is the name of repository and this section only shows official repositories, this way is it much redundant.

And if exists a plan for show unofficial repositories in this list, may be better put a flag with fewer featured.

<img width="1252" alt="screenshot 2015-08-12 11 31 49" src="https://cloud.githubusercontent.com/assets/1580446/9229323/f3db3522-40f2-11e5-95bc-f584b34ba2fa.png">

Sorry by my english, isn't my native language.

**Comment by ChristopherBiscardi** [comment]
The priority was shifted to the name of the repo for all cases and is pending a deploy.

As for expanding explore to include unofficial repos, that is a larger discussion revolving around how we might do large group-tagging in Hub.

**Comment by marcosalberto** [comment]
Thanks.
