### ISSUE TITLE
One day python27 worked as a repo to pull from the next it doesn't work

### ISSUE THREAD

**Issue by aussiev** [docker/hub-beta-feedback#255]
Seems there was a change somewhere:
In docker file:
FROM python27

worked on 8/8/2015

now on 8/12/2015 it doesn't,  what changed?

**Comment by ChristopherBiscardi** [comment]
You can see the available tags here: https://hub.docker.com/r/library/python/tags/

It seems that what you want is

```
FROM python:2.7
```

**Comment by nhsiehgit** [comment]
Is this still an issue or has this been resolved?

closing this ticket. if you feel it's been closed erroneously feel free to reopen and provide more context.
