### ISSUE TITLE
Links in Docker doc need to be updated

### ISSUE THREAD

**Issue by FrenchBen** [docker/hub-beta-feedback#263]
Probably more of a Docker docs issue, but since the push of the new hub, most Plans/Pricing/Billing links are broken:
https://docs.docker.com/docker-hub/
https://docs.docker.com/userguide/dockerrepos/#pushing-a-repository-to-docker-hub
...

**Comment by ChristopherBiscardi** [comment]
Links look like they've been fixed. closing

**Comment by FrenchBen** [comment]
:+1:
