### ISSUE TITLE
new UI is hard to find repository

### ISSUE THREAD

**Issue by forhot2000** [docker/hub-beta-feedback#266]
1. the newest repository is in the last page, we must goto the last page to open it, why not keep it in first page
2. the pager bar is too small, it only show at most 3 numbers as prev | current | next, we must click 4 times goto page 5, it is very terrible

![image](https://cloud.githubusercontent.com/assets/1013694/9244636/a81a0fa4-41cf-11e5-80a4-84e31c562d44.png)

**Comment by itzg** [comment]
:+1:

**Comment by nhsiehgit** [comment]
closing as this duplicates https://github.com/docker/hub-beta-feedback/issues/198

**Comment by itzg** [comment]
This doesn't seem to be a duplicate. This issue addresses the concern I have, as a repo owner, that my most popular and/or newer repos are showing up on page 2. They used to show most recent first, by default. From there users could sort by stars or number of downloads.
