### ISSUE TITLE
Linking Bitbutcket account to another account redirects to automated builds page without error 

### ISSUE THREAD

**Issue by eviltnan** [docker/hub-beta-feedback#267]
1. Link a bitbucket account A to docker hub account X
2. Log in in anonymous session with docker hub account Y
3. Log in to bitbucket with the same account A
4. Link bitbucket account A to docker hub account Y

Expected:
- error message, that account already used or relinking to account Y

Current:
- linking redirects back to link account page without any erro message or similar

**Comment by rrarunan** [comment]
A fix has been deployed.
