### ISSUE TITLE
Long email names interfere with 'verified' indicator

### ISSUE THREAD

**Issue by davidwilliamson** [docker/hub-beta-feedback#27]
environment: OS X + Chrome

After logging in, click on the gear icon to select account settings. If the user has an unusually long email address, the text bleeds over the 'verified' and 'primary' text, making things illegible. Seems to happen no matter how wide I make the browser window.

![screen shot 2015-06-04 at 9 46 22 am](https://cloud.githubusercontent.com/assets/6767139/7993401/cdde96a2-0aba-11e5-965b-3b8542dc5352.png)

**Comment by ChristopherBiscardi** [comment]
Making the browser window wider wouldn't necessarily help with this issue since the page has a max-width on the grid. We should likely be wrapping this value so the whole email still shows.

**Comment by nhsiehgit** [comment]
@biscarch wrap it or maybe add a scroll? or elipses?

**Comment by ChristopherBiscardi** [comment]
@nhsiehgit side-scroll is... displeasing to use. ellipses would cut off the `+` aliases and make all the emails look similar. (Imagine two emails `foo-wunderbar+...` and `foo-wunderbar+...`)

We *might* be able to do an ellipses if we displayed the full content on hover (or something fancy like that) but wrapping the content is the best, quickest, most resilient solution that solves the problem right now.

**Comment by ChristopherBiscardi** [comment]
This is fixed in prod. Closing.
