### ISSUE TITLE
Images with latest tag disappeared

### ISSUE THREAD

**Issue by dsampath** [docker/hub-beta-feedback#272]
All of our (private) repos had an issue post-migration. The images with latest tag had 0 bytes.
Also, the size reported for an image on the hub does not match the size of the image that we see locally and it doesn't seem like a rounding off error.

**Comment by dsampath** [comment]
![pasted_image_at_2015_08_13_02_39_pm_360](https://cloud.githubusercontent.com/assets/1567374/9262382/71b0797c-41c9-11e5-9113-39425466f722.png)
![pasted_image_at_2015_08_13_02_40_pm_720](https://cloud.githubusercontent.com/assets/1567374/9262386/78ef26de-41c9-11e5-8b48-a9d251e330c6.png)

**Comment by nhsiehgit** [comment]
hi @dsampath 
This looked like it was an issue with regards to the docker 1.8 release which was resolved with 1.8.1. 
If you're still on 1.8, could you try upgrading and letting us know if this is still an issue?

**Comment by dsampath** [comment]
Hey Nathan,

It went away with Docker 1.8.1.
You can go ahead and close this issue out.
Thanks  !

On Tue, Aug 18, 2015 at 3:22 PM, Nathan H <notifications@github.com> wrote:

> hi @dsampath <https://github.com/dsampath>
> This looked like it was an issue with regards to the docker 1.8 release
> which was resolved with 1.8.1.
> If you're still on 1.8, could you try upgrading and letting us know if
> this is still an issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/hub-beta-feedback/issues/272#issuecomment-132373481>
> .
>



-- 
--
Luminous beings we are, not this crude matter

**Comment by nhsiehgit** [comment]
perfect
