### ISSUE TITLE
Can't Update Billing Info

### ISSUE THREAD

**Issue by alsonkemp** [docker/hub-beta-feedback#274]
I'm trying to update an organization's billing info, but appear unable to do so.  Bits from the console:

Loading /u/someorg/dashboard/billing/:
GET https://hub.docker.com/v2/billing/account/someorg/transactions/ 500 (INTERNAL SERVER ERROR)

Click update billing info:
Various JS warnings.

@ /u/someorg/dashboard/billing/update-info/.  Update info.  Click Submit:
Web: crickets [no status, loading indicator, spinner, etc]
Console: 
POST https://hub.docker.com/v2/billing/account/undefined/billing_info/ 400 (BAD REQUEST)

Note: the "undefined" in the link is actually "undefined" and not "someorg", so JS appears busted.

**Comment by nhsiehgit** [comment]
This was brought to our attention and we have a PR in staging to address this. Sorry and thanks for your patience!

**Comment by nhsiehgit** [comment]
Closing as this should now be resolved! If you're still having issues please feel free to reopen with any additional information
