### ISSUE TITLE
New Docker Hub: Can't see mcandre/docker-jruby

### ISSUE THREAD

**Issue by mcandre** [docker/hub-beta-feedback#276]
I uploaded a container to the new Docker Hub: mcandre/docker-jruby, but I cannot see it online. When I try to create a repo named mcandre/docker-jruby, Docker Hub complains that it already exists.

**Comment by mcandre** [comment]
I can now see mcanre/docker-jruby on Docker Hub. Maybe there was a delay?

**Comment by nhsiehgit** [comment]
Hi @mcandre I was able to find your repo here: https://hub.docker.com/r/mcandre/docker-jruby/

closing for now since this seems to be a non-issue. If you feel there is still an issue here feel free to reopen and elaborate.
