### ISSUE TITLE
Search filter Official does not work

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/hub-beta-feedback#286]
![image](https://cloud.githubusercontent.com/assets/159209/9290530/1c51bd7c-434c-11e5-9d13-7e35eca92f31.png)

**Comment by rrarunan** [comment]
https://hub.docker.com/search/?q=ubuntu&page=1&isAutomated=0&isOfficial=1&pullCount=0&starCount=0 -> this works for me. Can you let me know what the query parameter was? If the query parameter was empty, the filters don't work at the moment. This is a known issue and we are working on a solution.

**Comment by kristiehoward** [comment]
An empty query (as shown in your screenshot @ahmetalpbalkan) no longer returns any results. The 'official' filter works on non-empty queries, so this is no longer an issue.

**Comment by ahmetalpbalkan** [comment]
hmm why doesn't it work on empty queries? I don't think this is intuitive. There are only a handful list of official images, you could've just listed them all in the empty query case.
