### ISSUE TITLE
Explore URL does not show all official images

### ISSUE THREAD

**Issue by ewindisch** [docker/hub-beta-feedback#29]
Only displays a subset of official images at: https://hub-beta.docker.com/explore/

![screen shot 2015-06-04 at 5 47 34 pm](https://cloud.githubusercontent.com/assets/73207/7995179/d875fbec-0ae1-11e5-86e6-d2cde3192261.png)

**Comment by tianon** [comment]
Seems like a pretty random ordering for them, too -- what's the sorting logic there?

**Comment by rrarunan** [comment]
deployed to beta. cc @fxdgear @kencochrane ^^ for @tianon's question. Closing this issue, since the pages are now available and show all the repos.

**Comment by ChristopherBiscardi** [comment]
@tianon I created a ticket for the sort ordering #91 The current sorting is the default sorting, which is last_updated.
