### ISSUE TITLE
Cursor keys don't work in hub registration text forms

### ISSUE THREAD

**Issue by stain** [docker/hub-beta-feedback#291]
Using Firefox 40.0/Ubuntu 14.04 it is impossible to edit text in any description fields of the hub, e.g. when trying to adding a new repository. If I use cursor keys like left arrow or home, and type a letter, the first letter is added correctly, but the next letters are added at the end of the text field.

E.g. editing the Short Description

> Fred

to "Mr. Fred"  by clicking Home and typing "Mr. " becomes

> MFredr. 

There seems to be a javascript interfering.

**Comment by stain** [comment]
This also happens if I position the cursor with the mouse.

**Comment by ChristopherBiscardi** [comment]
Closing as duplicate of #93 since this will be solved globally
