### ISSUE TITLE
Collaborative Private Repo Not Visible

### ISSUE THREAD

**Issue by stooie90** [docker/hub-beta-feedback#293]
I cannot see private repos from my dashboard that I'm marked as a collaborator in. I'm still able to access the repo, I just needed to have access to the link and I can also star it to gain access. But as far as I can see there is no other way for me to be able to access that repo if I had no way of finding the link.

**Comment by rrarunan** [comment]
@stooie90 Is the repository part of an organization or a user? i.e what is the `namespace` in `<namespace>/<repo_name>` ? A user or an organization?

**Comment by stooie90** [comment]
@rrarunan the repository belongs to another user, not an organisation.

**Comment by rrarunan** [comment]
@stooie90 This is a bug. The dashboard should also show repos that you are collaborator on. We will fix it and provide an update here. Thanks for the report!

**Comment by rrarunan** [comment]
@stooie90 Fix was deployed. You should see the repositories you are collaborator on in the `Contributed` section in the dashboard.

**Comment by IKOBH** [comment]
Issue repeats
