### ISSUE TITLE
Unable to change to a Medium size organization repository 

### ISSUE THREAD

**Issue by clarksc** [docker/hub-beta-feedback#295]
Hi ,
The submit button on the billing page does not allow you to update from the free trial to a multiple repository package.  I am trying to go to a Medium solution and the screen just sits there when I press the submit button.

Thanks,

**Comment by nhsiehgit** [comment]
Hi @clarksc,

There have been some issues with our billing pages the past week. We've recently deployed some changes to help pacify some of the current errors. Can you try again and let us know if you are still seeing issues?

**Comment by nhsiehgit** [comment]
relates to: https://github.com/docker/hub-beta-feedback/issues/274

**Comment by clarksc** [comment]
Hi Nathan,
 yes, I an still not able to submit from the billing page. The submit button now has a spinning image, but it still doesn't complete the transaction.
Scott



Sent from my Samsung device over Bell's LTE network.


-------- Original message --------

**Comment by nhsiehgit** [comment]
Thanks @clarksc 
A few questions to help us debug the issue:
- Is this for updating your billing information or for creating a new subscription?
- Are you attempting to upgrade a user account or an organization?
- On submit, does the call ever complete or is the spinner just stuck on the page?

Thanks for the help!

**Comment by clarksc** [comment]
1. We originally had one repository. We need the 20 repository plan for our dev team. I was added to our organization as a new owner so that I could pay for these 20 repos.
2.I'm trying to give the qlik organization (of which I am a new owner) the medium plan.
3. Yep. Sooner gets stuck on the page.

Btw, I also noticed that province or state is not part of the billing form. Does that not cause a possible with the validation of the credit card our is that caught by the postal code?

Developers are getting pretty frustrated because I need to get them at least 5-10 private repos asap.

Anything you can do to make this happen uhh the short term would really go a long way in helping us with this docker hub infrastructure.

Thanks Nathan.
Scott


Sent from my Samsung device over Bell's LTE network.


-------- Original message --------

**Comment by nhsiehgit** [comment]
Sorry for all the troubles!

Thanks for this information. Yes there's a handful of issues we're working through right now so this definitely helps pin point some of our issues.

For now, i'd suggest contacting our [support team](support.docker.com) to help set up the subscription if you need it asap. They'll be able to help you sort out the plan until we're able to get a fix up on prod. 

Thanks for your patience!

**Comment by clarksc** [comment]
Could I ask you to send the request to them on my behalf?
If your support team is similar to ours, sometimes the link from the development team is quicker than the customer link.
:)
Just wondering.
Scott



Sent from my Samsung device over Bell's LTE network.


-------- Original message --------

**Comment by nhsiehgit** [comment]
NP already sent the issue over to them so hopefully they will repsond sooner rather than later.
I'd still suggest creating a ticket for them to track as well though

**Comment by fauzanariffin** [comment]
Hi @clarksc,

Can you please send an email to support@docker.com? Please include this page [URL](https://github.com/docker/hub-beta-feedback/issues/295) in the email so that we can track the history of the issue.

Thanks!

Regards,
Fauzan
Docker Support Team

**Comment by clarksc** [comment]
Sounds good.
Support address is ...



Sent from my Samsung device over Bell's LTE network.


-------- Original message --------

**Comment by nhsiehgit** [comment]
hi @clarksc The billing pages should be up to date now. If you still haven't been helped would you be able to confirm whether the billing pages now work for you?

Thanks!

**Comment by clarksc** [comment]
Nope – Still can’t see province when I Click on Canada.




Scott Clark
Director, Product Area Architect – Quality Engineering

Mobile: +1 613-355-4104
Skype: scottottawa
Email:  Scott.Clark@qlik.com

Qlik


qlik.com<http://www.qlik.com/>
[qlik.com]<http://www.qlik.com/us/explore/products/sense?SourceID1=Corporate_Email_Signature>

The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error, please contact the sender and delete the material from any computer.

**Comment by nhsiehgit** [comment]
Woops sorry i misspoke. We'll be deploying prod ETA 3pm PST. Sorry again for the wait.

**Comment by nhsiehgit** [comment]
Sorry, once more @clarksc 

Didn't realize we hadn't actually deployed to production yet, but just confirmed it's up and the state input should be included in the billing form now.

Thanks again,

**Comment by nhsiehgit** [comment]
Closing as this should be fixed now
