### ISSUE TITLE
Bitbucket repositories not listed for automated build

### ISSUE THREAD

**Issue by orlade** [docker/hub-beta-feedback#299]
I'm trying to create a private automated build from a private Bitbucket repository. I click "Create > Create automated build" which loads a page with GitHub and Bitbucket buttons. I click GitHub and my GitHub repos are listed. I click Bitbucket and nothing is listed, just an empty "Users/Organizations" list. I believe both are linked correctly.

Using Windows 10 and both Chrome and Firefox.

**Comment by ChristopherBiscardi** [comment]
Thanks for reporting. 

@rrarunan can you take a look at this?

**Comment by rrarunan** [comment]
@orlade We had an issue with bitbucket links when we GA'ed version 2 of the hub. Please let us know if this bitbucket link has always existed in your hub account. If so, can you revoke access from bitbucket, unlink your account from the docker hub and let us know if that fixes it. Also, can you please share your `hub username` in an email to `support@docker.com`.

**Comment by orlade** [comment]
The link had existed from v1, and unlinking and re-linking did indeed fix the problem. Thanks for that!

I know it's crufty, but maybe show a notification if Bitbucket repos fail to load?

**Comment by rrarunan** [comment]
@orlade thanks for the update! Yes, that fix to provide feedback is slated for sometime this week.

**Comment by fluidicsw** [comment]
I seem to have the same problem. GitHub repositories seem to be picked up correctly, but out of possibly even over hundred repositories in BitBucket, I can see single, pretty random one (I have double-checked permissions and there does not seem to be anything special about that single visible repository, on the BitBucket side).
