### ISSUE TITLE
Unauthorized users given option to add teams to orgs they cannot admin

### ISSUE THREAD

**Issue by ewindisch** [docker/hub-beta-feedback#30]
I am a member of a team I am (presumably) not authorized to admin. I am given the link to create a Team within this organization. The add team page loads, but fails to submit.

![screen shot 2015-06-04 at 5 51 16 pm](https://cloud.githubusercontent.com/assets/73207/7995257/518d1420-0ae2-11e5-945e-f4880a7d9413.png)

**Comment by rrarunan** [comment]
We need to either lock down or disable pages from being available like for eg. the team profile page if the user does not have access (OR) leave it as is currently and address this as we overhaul the orgs/teams workflow pages in their entirety.

**Comment by rrarunan** [comment]
Same issue discussed in #156

**Comment by nhsiehgit** [comment]
closed also with https://github.com/docker/hub-beta-feedback/issues/156
