### ISSUE TITLE
docker push succeeds but image never shows up on Docker Hub

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/hub-beta-feedback#307]
1. `docker push`ing to a non-existing repo succeeds (why?)
2. `docker push`ing to a repo succeeds, too. But the build never shows up on Docker Hub.

Is there a livesite issue going on?

> EDIT: looks like #301 and #306 are pretty much reporting the same problem.

----

#### 2. `docker push` image

```bash
$ docker tag busybox ahmetalpbalkan/busy:latest
$ docker push ahmetalpbalkan/busy:latest
The push refers to a repository [docker.io/ahmetalpbalkan/busy] (len: 1)
8c2e06607696: Image already exists
6ce2e90b0bc7: Image successfully pushed
cf2616975b4a: Image already exists
latest: digest: sha256:491ca41e17910e3d1eab9a683edbfc9e34e2f987da28e7242ebfd4324ae0f807 size: 5064
```

#### 3. Go to “Tags” tab, nothing shows up...

-------

cc: @garimakhulbe

**Comment by rrarunan** [comment]
@ahmetalpbalkan we are looking into this.

**Comment by ahmetalpbalkan** [comment]
@rrarunan thanks, please keep us updated.

**Comment by dmp42** [comment]
@ahmetalpbalkan see linked issue on docker

**Comment by ahmetalpbalkan** [comment]
@dmp42 thanks for the update.

**Comment by thaJeztah** [comment]
@ahmetalpbalkan can you check if this has been resolved?

**Comment by ahmetalpbalkan** [comment]
@thaJeztah yes, looks like it's working now. Thanks.

**Comment by mc388** [comment]
I have the same issue since a few days unit now.

**Comment by thaJeztah** [comment]
@mc388 I think last time this was caused by a longer than usual queue in Docker Hub. Could you open a ticket via https://support.docker.com, the support team there should be better able to look into your case.

**Comment by mc388** [comment]
@thaJeztah ok thanks

**Comment by adligo** [comment]
+1

**Comment by ingshtrom** [comment]
This is an old issue. Please open a new one with details on the image which was pushed, timestamps of when you pushed and when you checked Docker Hub. The account with which the image was pushed might be helpful as well.

If you have a Docker Pro, Docker Team, or Docker Business account with us, you can also [create a support ticket](https://hub.docker.com/support/) to get official support from us.

It is also worth noting that some of our providers have had several major issues over the last two weeks, which caused our queues to back up, which also contributes heavily to this.

**Comment by thaJeztah** [comment]
Let me lock the conversation on this one, to prevent new comments (as they're likely unrelated, or at least very easy to be overlooked on GitHub)
