### ISSUE TITLE
Adding/deleting users in team appears to work, but fails

### ISSUE THREAD

**Issue by ewindisch** [docker/hub-beta-feedback#31]
On refresh, new users disappear. When deleting a user, refreshing brings the user back...

![swn7r5jzgk](https://cloud.githubusercontent.com/assets/73207/7995416/8c3b56b2-0ae3-11e5-8648-bd4789c75b71.gif)

It's possible / likely I'm not authorized, but I should still expect an error.

**Comment by ChristopherBiscardi** [comment]
The Teams pages have been rewritten. Closing this.
