### ISSUE TITLE
Automated docker build fails with exception

### ISSUE THREAD

**Issue by macnibblet** [docker/hub-beta-feedback#319]
I have a private automated build that should compile ffmpeg, but on each attempt it ends with `exception` and that's just about all i know.

**Comment by ChristopherBiscardi** [comment]
@macnibblet Please contact support@docker.com who will ask you for more information (repo name, build id, etc).

For reference the automated build limits are:

* 2 hours maximum build time
* 2 GB RAM
* 1 CPU
* 30 GB Disk Space

**Comment by Kaixhin** [comment]
Is it possible to get automated information, or even the logs, when an `exception` appears as the status? Until I was aware of the automated build limits I tried redoing builds thinking that it was a temporary issue.
