### ISSUE TITLE
Create Org "invalid" errors should reset when input is corrected

### ISSUE THREAD

**Issue by ewindisch** [docker/hub-beta-feedback#33]
When invalid input is given on the org create page, the invalid-input errors should be removed.

![udihvbncan](https://cloud.githubusercontent.com/assets/73207/7995576/3bd1c1e6-0ae5-11e5-839f-9303015cc7e0.gif)

**Comment by ewindisch** [comment]
(relatedly, gopher should be a valid protocol :smile: )

**Comment by rrarunan** [comment]
There are two separate issues here, I see.
1) we are not clearing the error states `onChange` of the text input fields.
2) the API is not accepting certain protocols in the website URL. (this probably needs a separate issue)

**Comment by ChristopherBiscardi** [comment]
Related to **2)** The API only validates http(s) urls for a reason I am not familiar with. iirc it is like this on the old hub as well.

**Comment by ewindisch** [comment]
I agree the protocol should be a separate issue, if it's one at all. I was joking about Gopher...

**Comment by ChristopherBiscardi** [comment]
I was mostly commenting on the fact that urls won't work if they are specified as `www.whatever.com` iirc; only `https://www.whatever.com`. (I barely even know how gopher works)

**Comment by ChristopherBiscardi** [comment]
Closing:

![website_url](https://cloud.githubusercontent.com/assets/551247/9312098/7d33dcc2-44cf-11e5-8cc2-42eec5b78bb2.gif)
