### ISSUE TITLE
r/username url renders very badly

### ISSUE THREAD

**Issue by ewindisch** [docker/hub-beta-feedback#34]
Urls such as the following render terribly: https://hub-beta.docker.com/r/ewindisch/

Users can navigate to this directly, although I actually received a link to this from a listing for the repository "ewindisch/." (which I successfully created before an earlier bug was resolved)

![screen shot 2015-06-04 at 6 18 20 pm](https://cloud.githubusercontent.com/assets/73207/7995682/6600c790-0ae6-11e5-8c8e-a78ae8e91bf8.png)

**Comment by rrarunan** [comment]
We might need to remove this from the routes or redirect to the `/u/<username>` route.

**Comment by ChristopherBiscardi** [comment]
@rrarunan yes. I think the profiles urls replace this. This should probably redirect to the profile `/u/:user/` since the default view is a user's repos.

**Comment by ChristopherBiscardi** [comment]
@rrarunan We should make sure this page is gone by DockerCon I think.

**Comment by rrarunan** [comment]
deployed to beta.
