### ISSUE TITLE
[UI] bottom of letters cut-off in "org context" drop-down box

### ISSUE THREAD

**Issue by j0hnst0n** [docker/hub-beta-feedback#35]
Org names with letters with below-the-line elements (g, j, q, etc) are getting cut-off in the drop-down menu:
![image](https://cloud.githubusercontent.com/assets/1610391/7997083/c4177d88-0adc-11e5-9981-70347ca73f8a.png)

**Comment by ChristopherBiscardi** [comment]
@jsouth Can you take a look at this one?

**Comment by ChristopherBiscardi** [comment]
This was fixed in the last deploy.
