### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by ChristopherBiscardi** [docker/hub-beta-feedback#36]
The entire site is missing pagination on all fronts. This needs to be fixed.

- [x] User Profile Repos
- [x] User Profile Stars
- [x] Dashboard Repos
- [x] https://github.com/docker/hub-beta-feedback/issues/14 - Repository Comments 
- [x] https://github.com/docker/hub-beta-feedback/issues/52 Search Results
- [x] https://github.com/docker/hub-beta-feedback/issues/29 - Explore (Official Images)

**Comment by cpswan** [comment]
I'm seeing this at the bottom of my account repository page, which seems similar to #47 

    << 1 NaN >>

Browser and Browser version: ```Chrome 43.0.2357.124 m```
URL for the page in question: ```https://hub-beta.docker.com/```
The rough date and time the error occurred (be sure to include your time zone): ```201506151400Z```
Your hub username: ```cpswan```
Screenshots of the issue:
![image](https://cloud.githubusercontent.com/assets/478926/8161603/27e4345a-1370-11e5-84a9-663b471abd00.png)

**Comment by rrarunan** [comment]
Update: Pagination is up on the user dashboard (not profile yet: /u/<user> | coming soon...) and the explore official repos page.

**Comment by trsouz** [comment]
This is a case of "user experience" but I think enters into the paging topic (let me know if it's not).

I realized that when you click on the next page (and previous), have no feedback whether it is loading or not. And when the request ends it does not take the page to the top position.

Url: https://hub-beta.docker.com/explore/

Other comments:
  - Pagination displays button only to the current page
  - Does not display total pages count
  - When only has a one page, don't display pagination component. (observed in the comment components like in: https://hub-beta.docker.com/_/cassandra/)

**Comment by ChristopherBiscardi** [comment]
@trsouz that's perfectly acceptable feedback for this ticket. Thanks for taking the time to write it up.

**Comment by cpuguy83** [comment]
pagination on the repos list is non-intuitive.

![screen shot 2015-08-07 at 10 01 55 am](https://cloud.githubusercontent.com/assets/799078/9137418/599ea99a-3ceb-11e5-87ca-4a2006e4cd7f.png)

I see this and it looks like there's no other pages, but of course there are.

**Comment by thaJeztah** [comment]
Had the same impression as @cpuguy83, going to the official images page and thought; just *one* page?

**Comment by ofir-petrushka** [comment]
@cpuguy83 at least yours renders a bit different on the right, this is mine.
![docker_pagination](https://cloud.githubusercontent.com/assets/9718419/9160325/ee711560-3f40-11e5-8e57-faf7b289b8fa.png)

Chromium Version 43.0.2357.130 Ubuntu 15.04 (64-bit)

**Comment by rrarunan** [comment]
Closing this ticket and tracking (adding pagination for the `stars` on the dashboard in this ticket (https://github.com/docker/hub-beta-feedback/issues/243).

**Comment by tedyoung** [comment]
Not sure why this is closed: today I encountered this (looking at https://hub.docker.com/r/library/nginx/):

![paging-p1](https://cloud.githubusercontent.com/assets/382660/9588521/bb8d692a-4fdd-11e5-85f9-07435e398b7d.png)

So I'm thinking: "oh, only one more page", so I click on the [2], and then I'm surprised to see:

![paging-p2](https://cloud.githubusercontent.com/assets/382660/9588554/e7bb0c96-4fdd-11e5-87b8-35fdc2b34868.png)

And I'm thinking: "what?" It's totally unexpected.
