### ISSUE TITLE
Gravatars of users not showing up on repo cards

### ISSUE THREAD

**Issue by rrarunan** [docker/hub-beta-feedback#37]
Currently we see the docker icon on all repositories, it would be better to show the `namespace` owner's avatar instead.

**Comment by ChristopherBiscardi** [comment]
+1 on this. The reason we don't have this right now is API performance because of the way we store them :disappointed:

**Comment by ChristopherBiscardi** [comment]
Since it looks like we might have this after DockerCon I'm adding it to GA

**Comment by ringods** [comment]
+1

**Comment by ChristopherBiscardi** [comment]
We have user gravatars implemented in most places.Closing.
