### ISSUE TITLE
User/Org selection dropdown defaults to top A-Z sorted item instead of User account.

### ISSUE THREAD

**Issue by kizbitz** [docker/hub-beta-feedback#38]
Same on Chrome and Firefox.

- Log out
- Close all hub-beta tabs
- Open new tab with https://hub-beta.docker.com
- Log In
- Default dropdown item is the top item in the sorted org/user list instead of the logged in user.

![screen shot 2015-06-05 at 11 24 18 am](https://cloud.githubusercontent.com/assets/201920/8009325/172c8416-0b76-11e5-89c3-08cdf7097fea.png)

**Comment by rrarunan** [comment]
latest deploy doesn't have this issue.
