### ISSUE TITLE
Create repository form: Visibility private by default

### ISSUE THREAD

**Issue by rrarunan** [docker/hub-beta-feedback#40]
- [x] The form should pick the global settings of the user to have `private` or `public` by default
- [x] Also, need to fix error response when private repos aren't available anymore for eg.

**Comment by nhsiehgit** [comment]
This should be finished. closing now

**Comment by rrarunan** [comment]
deployed to beta.

**Comment by apuatcfbd** [comment]
How to set newly created repo to type private by default or
How to push new images to private repo?
