### ISSUE TITLE
Username not showed correctly

### ISSUE THREAD

**Issue by gopalfreak** [docker/hub-beta-feedback#42]
Username in my case with a small "g" in beginning is cutted / wrong rendered in the namebox.
This is in actual FF 38.0.5 and Chrome Version 43.0.2357.124 m
 the case...
![username_ff](https://cloud.githubusercontent.com/assets/8685067/8126669/ea0452c2-10f0-11e5-8ac7-ea1464c4dfcd.JPG)
![username_chrome](https://cloud.githubusercontent.com/assets/8685067/8126672/ecca3ec2-10f0-11e5-9832-4dc74abef70f.JPG)

The other username buttons / labels seem to work properly...

**Comment by rrarunan** [comment]
duplicated by #35 . Closing this one.
