### ISSUE TITLE
Reset Password broken

### ISSUE THREAD

**Issue by jbdalido** [docker/hub-beta-feedback#43]
Hello, 
The reset workflow is working until we click the reset link, the confirm page send 200 but the page is empty.
Here's the console output :

    No route matches path "//account/password-reset-confirm/*****/**********************/". Make sure you have <Route path="//account/password-reset-confirm/********/**************/"> somewhere in your routes

Thanks.

**Comment by ChristopherBiscardi** [comment]
The link has been fixed
