### ISSUE TITLE
Can not see the repositories of the organisation i belong to.

### ISSUE THREAD

**Issue by sebest** [docker/hub-beta-feedback#44]
My username is 'sebest' and belong to organisation 'pixelle', when i select it in the dropdown menu, the list was empty with the blank slate to create a new one.

I created one and it was the only one appearing.

On the old interface i can see all of them

**Comment by rrarunan** [comment]
Deployed to beta. @sebest See if you can create a repo from the `pixelle` organization namespace. Let us know if it still does not work for you. Closing until then.
