### ISSUE TITLE
Link to the organisation name in a repository detail page returns 404

### ISSUE THREAD

**Issue by sebest** [docker/hub-beta-feedback#45]
I created a repository in my organisation:
https://hub-beta.docker.com/r/pixelle/test/

Under the label "private repository" there is a link:
https://hub-beta.docker.com/u/pixelle/

it returns a 404

**Comment by ChristopherBiscardi** [comment]
Thanks for the report.

This was recently addressed (recently = today) by a PR to the service giving us the data for users/orgs. It should be fixed when that service is deployed again.

**Comment by rrarunan** [comment]
@ChristopherBiscardi Doesn't seem to be fixed yet. Will take a look.

**Comment by ChristopherBiscardi** [comment]
The provided links no longer 404 for me.
