### ISSUE TITLE
Organisation repositories: page 1, page NaN

### ISSUE THREAD

**Issue by oncletom** [docker/hub-beta-feedback#47]
![screen shot 2015-06-12 at 21 07 56](https://cloud.githubusercontent.com/assets/138627/8139129/fafef5b6-1148-11e5-862d-91666249f6a0.png)

A click on the *NaN* button has no effect so can't tell if I was supposed to be able to paginate.

**Comment by ChristopherBiscardi** [comment]
Thanks for the report!

I'm going to close this in favor of https://github.com/docker/hub-beta-feedback/issues/36 which is tracking Pagination across the site.

**Comment by oncletom** [comment]
:+1:
