### ISSUE TITLE
"last updated: a few seconds ago" is displayed whereas the repo has been updated several months ago

### ISSUE THREAD

**Issue by oncletom** [docker/hub-beta-feedback#48]
![screen shot 2015-06-12 at 21 23 36](https://cloud.githubusercontent.com/assets/138627/8139162/5e32d346-1149-11e5-86b0-aa20bf324d9f.png)

This is what reports the current Docker Hub page:

![screen shot 2015-06-12 at 21 25 33](https://cloud.githubusercontent.com/assets/138627/8139195/a026e3b4-1149-11e5-8466-9df52814ba7d.png)

**Comment by kencochrane** [comment]
I think this one has been fixed, we can probably close it out.

**Comment by rrarunan** [comment]
Yes verified it. Closing.
