### ISSUE TITLE
Repo navigation between "Settings" and "Repository" is unclear

### ISSUE THREAD

**Issue by oncletom** [docker/hub-beta-feedback#49]
![docker-hub-beta-settings](https://cloud.githubusercontent.com/assets/138627/8139225/cf1319ae-1149-11e5-8b24-28083565175f.gif)

It took me a couple of seconds to get I was still on the same repo —but moved from a "public facing"  navigation to an "repo admin" navigation.

Plus it is weird to have a different *repository* icon (a box) than the top menu "Create a new repository" (a book).

**Comment by ChristopherBiscardi** [comment]
@jsouth This is relevant to the discussion we were having the other day. As long as we can fit all the options in the sub-nav I think we should move to a singular sub-nav. There's less of a clear distinction between the options then I thought there was going to be.

![screenshot 2015-06-12 13 55 32](https://cloud.githubusercontent.com/assets/551247/8139717/b8b28468-110a-11e5-9b85-ec4f86adb7c4.png)

**Comment by rrarunan** [comment]
We changed it to be similar to @ChristopherBiscardi 's previous comment. Closing this one.
