### ISSUE TITLE
Dockerfile appearance on automated build is bad

### ISSUE THREAD

**Issue by nathanleclaire** [docker/hub-beta-feedback#5]
Check it out: 

![image](https://cloud.githubusercontent.com/assets/1476820/7974559/fc79c854-0a17-11e5-8690-73bd3b0da052.png)

It should definitely use a Monospace font, and not bleed off the edges of the box like that.

I'm using Chrome (recent) on OSX.

**Comment by ChristopherBiscardi** [comment]
@nathanleclaire Please re-open this if the new styles are still sub-par. Both the monospace font and the bleed have been addressed

URL to above repo for convenience:
https://hub-beta.docker.com/r/jplock/zookeeper/~/dockerfile/

**Comment by nathanleclaire** [comment]
@ChristopherBiscardi I don't see anything in the Dockerfile box on that page:

![screen shot 2015-06-16 at 10 26 13 am](https://cloud.githubusercontent.com/assets/1476820/8189807/a52ce0da-1413-11e5-90b4-c06fda5bff80.png)

**Comment by ChristopherBiscardi** [comment]
@nathanleclaire That's a different bug relating to the fact that you're not logged in.

**Comment by nathanleclaire** [comment]
Ah.  Would you like me to file something for that?  The Dockerfiles appear fine when logged in.

**Comment by ChristopherBiscardi** [comment]
I thought we had something for it already but I can't find it. @nathanleclaire yes, please file.
