### ISSUE TITLE
Search results page lacks 'next page of results' navigation

### ISSUE THREAD

**Issue by davidwilliamson** [docker/hub-beta-feedback#52]
Typing (for example) 'busybox' into the search box returns and displays 10 results. However, the JSON response (using chrome developer tools) says there are actually 331 hits.

```
{"count": 331, "next": "https://registry.hub.docker.com/v2/search/repositories/?ordering=&query=busybox&is_automated=false&page=2" "previous": null, "results": [{ ...} ... ]
```

The results page needs controls so the user display the next/previous page of results.

**Comment by ChristopherBiscardi** [comment]
Closing this in favor of https://github.com/docker/hub-beta-feedback/issues/36 which details the work that needs to go into Pagination across the site
