### ISSUE TITLE
Password security?

### ISSUE THREAD

**Issue by zopyx** [docker/hub-beta-feedback#54]
It is possible to create a new account with a three char password.

Are you serious about security?

Do you know what you are doing?

As always: #Docker devs are incompetent by all means and give a shit about security. Security seems to be an unknown word to you?

**Comment by willfong** [comment]
Shouldn't it be the user who wants to use a three character password be the one incompetent about security? 

I actually really hate it when websites force me to use "secure" passwords with different rules for the password. Some want various length, some enforce "two of the three ways to be secure", some disallow special characters, bla bla bla. What if I don't use this account for anything sensitive? It's not like I'm putting in access credentials or personal/financial information here. Let me do things my own way, as stupid as it sounds. It's not going to affect you.

As long as the website uses a secure connection, I'd be happy as a clam :)

(and, for the record, I do use Lastpass...)

**Comment by zopyx** [comment]
What a stupid argumentation....

2015-06-15 2:25 GMT+02:00 Will Fong <notifications@github.com>:

**Comment by thaJeztah** [comment]
https://hub-beta.docker.com/account/settings/

Looks like it was "improved", but fully agree, 4 chars is crazy.

> Please choose a password which is longer than 4 characters.

@willfong 

> As long as the website uses a secure connection, I'd be happy as a clam :)

How does a secure connection help protecting a brute force on a 3-char password?


(Yes, the final responsibility lies with the user, but 4 chars just isn't right)

**Comment by willfong** [comment]
@thaJeztah There are many ways to mitigate a brute force attack, which should already be in place. Accounts should be [temporarily] locked after a set number of failed logins. 2-factor authentication. Login throttling. And at least, one would hope logs are monitored for suspicious activity. 

Then the other question of why are we continually reinventing the online authentication wheel? OpenID anyone? We should be spending time on building the future here.

Password length is a false sense of security.

**Comment by ChristopherBiscardi** [comment]
Minimum password length is 6. Closing.

**Comment by zopyx** [comment]
LOL..6 chars...security made by idiots for idiots

2015-08-07 1:43 GMT-07:00 Christopher Biscardi <notifications@github.com>:

**Comment by frekele** [comment]
https://github.com/docker/hub-feedback/issues/358

**Comment by frekele** [comment]
Related Issue: https://github.com/docker/hub-feedback/issues/358

**Comment by joeldrapper** [comment]
@zopyx have you tried Rancher? They seam to give a damn about security.
