### ISSUE TITLE
Another thumbs up for the new design.   

### ISSUE THREAD

**Issue by Sing-Li** [docker/hub-beta-feedback#56]
Uncluttered.  Easier than ever to find what I need.    :+1:     Kudos.

PS... Will put it through its pace over next few weeks and hopefully file some bugs.

**Comment by ChristopherBiscardi** [comment]
Thanks :smile:  Happy to hear you're finding it easy to use.

**Comment by ChristopherBiscardi** [comment]
Thanks for the feedback. Going to close this now to focus the board on bugs and feature requests :)
