### ISSUE TITLE
Notifications page traps you

### ISSUE THREAD

**Issue by nathanleclaire** [docker/hub-beta-feedback#6]
Steps to reproduce:

1. Navigate to https://hub-beta.docker.com/account/notifications/
2. Try clicking on any other link including the whale in the upper left hand corner
3. The links don't work for me

I have to enter hub-beta.docker.com in my browser to escape.

**Comment by ChristopherBiscardi** [comment]
Thanks for reporting :grinning: 

-- The `executeAction` in transition hooks isn't behaving correctly. quick-fix is to remove the action for now.

**Comment by nhsiehgit** [comment]
Is it a problem with executeAction or with the router transitionFrom? 
https://github.com/docker/hub2-demo/blob/master/app/scripts/components/account/NotificationsSettings.jsx#L32-L34

**Comment by ChristopherBiscardi** [comment]
@nhsiehgit The issue is that the `context` doesn't have a function called `executeAction`. It's definitely an issue in the `willTransitionFrom` block though.

![screenshot 2015-06-04 09 09 52](https://cloud.githubusercontent.com/assets/551247/7988674/81fa2966-0a99-11e5-9aa1-2ef019e1cd21.png)

**Comment by ChristopherBiscardi** [comment]
Notifications page no longer traps the user.
