### ISSUE TITLE
Repositories page shows NaN

### ISSUE THREAD

**Issue by mchiang0610** [docker/hub-beta-feedback#60]
URL: https://hub-beta.docker.com/u/kitematic/dashboard/
OS: Mac OS X Yosemite 10.10.3 
Browser: Chrome 43.0.2357.124 (64 bit) 
Date: June 15th, 4pm
Hub username: mchiang

![image](https://cloud.githubusercontent.com/assets/3325447/8172721/5b46d2a0-1378-11e5-8476-c0c51206205e.png)

**Comment by rrarunan** [comment]
Pagination #36 is the issue tracking pagination work across the site. Closing this one in favor of the bigger issue.
