### ISSUE TITLE
Default to 'Repositories' page instead of the 'Teams' settings page when selecting an organization.

### ISSUE THREAD

**Issue by kizbitz** [docker/hub-beta-feedback#63]
When using the menu links (not the drop down) to select an organization the landing page is the teams settings page instead of the repositories page.

- Click 'Organizations' in the top main nav bar
- Select an organization > Results in team settings page

Using the drop down lands on the organizations repositories page.

**Comment by rrarunan** [comment]
I agree we have to make this consistent. I'm +1 on this and am okay with making the change.

**Comment by ChristopherBiscardi** [comment]
@rrarunan To be clear, you think we should change the settings page Org list items to point to the dashboard of the Org?

At first blush I was against this but after thinking about it I think it would help to reinforce the idea of "Dashboard as entrypoint". Just want to make sure it's not confusing that people are sent from `page A` -> `page B` -> `page-that-looks-a-lot-like A`

**Comment by rrarunan** [comment]
@ChristopherBiscardi Yes, actually since the settings page orgs list don't exist in the settings page anymore, it makes more sense too. If it still does exist within the settings pages, I have one more thing to fix.

**Comment by rrarunan** [comment]
Deployed to beta.
