### ISSUE TITLE
Add feedback/notification to team details form

### ISSUE THREAD

**Issue by kizbitz** [docker/hub-beta-feedback#64]
Need feedback/notification that the save was successful (or not) on the teams details form

![screen shot 2015-06-16 at 6 49 11 am](https://cloud.githubusercontent.com/assets/201920/8181446/fbb45bec-13f3-11e5-800a-a7e057cbec7a.png)

**Comment by kencochrane** [comment]
We also need it on the Edit team page as well. If you don't have permission to edit it, you don't get any feedback, so you don't know if it worked or not. For the save or the delete.

**Comment by rrarunan** [comment]
@kencochrane @kizbitz We are currently removing the add/update form for the orgs that the current user is not an owner. So, this should fix that.
