### ISSUE TITLE
Private repositories indicators do not update when selecting an organization

### ISSUE THREAD

**Issue by kizbitz** [docker/hub-beta-feedback#66]
When managing an organization the private repositories indicator should reflect the number of private repositories available for the organization instead of the user account.

In this screen shot it is still showing my personal private repos

![screen shot 2015-06-16 at 8 21 10 am](https://cloud.githubusercontent.com/assets/201920/8182791/fe0e77bc-1400-11e5-9f95-c4593c7e20c7.png)
 
---

Compared to current hub:

![screen shot 2015-06-16 at 8 24 28 am](https://cloud.githubusercontent.com/assets/201920/8182800/20eee348-1401-11e5-8957-b58c60d573dd.png)

**Comment by ChristopherBiscardi** [comment]
This is deployed
