### ISSUE TITLE
Password reset url not working

### ISSUE THREAD

**Issue by cptactionhank** [docker/hub-beta-feedback#69]
I reset my password and the email i was sent contained the url https://hub-beta.docker.com//account/password-reset-confirm/xxx, however I'm only presented with a blank page.

```javascript
Warning: No route matches path "//account/password-reset-confirm/MjYwMTA/42n-c3f180f6970a05daf26c/". Make sure you have <Route path="//account/password-reset-confirm/MjYwMTA/42n-c3f180f6970a05daf26c/"> somewhere in your routes
```

the working url would be https://hub-beta.docker.com/account/password-reset-confirm/xxx, notice only a single `/` after the hostname.

**Comment by josephwinston** [comment]
Same issue here.

**Comment by TeckniX** [comment]
Probably fix the required button * overlay too:

![resetpassword](https://cloud.githubusercontent.com/assets/33699/8605743/490b7344-2655-11e5-9edb-624124086795.png)

**Comment by ChristopherBiscardi** [comment]
@TeckniX that looks like lastpass inserting icons. Can you confirm that you have an autofill form plugin enabled?

**Comment by TeckniX** [comment]
@ChristopherBiscardi you're right, I do have last pass enabled. Odd that it shows the button * , when it doesn't on other login/signup pages.

**Comment by ChristopherBiscardi** [comment]
@TeckniX I'm going to create a new ticket to track the lastpass issue since this ticket is about the reset-password url, which has been fixed
