### ISSUE TITLE
Bad text rendering in search box

### ISSUE THREAD

**Issue by kizbitz** [docker/hub-beta-feedback#7]
![screen shot 2015-06-04 at 10 22 51 am](https://cloud.githubusercontent.com/assets/201920/7986252/6c69434c-0aa4-11e5-84c6-aa472b004f20.png)
Firefox 38.0.5

**Comment by ChristopherBiscardi** [comment]
@jsouth this is due to the padding overrides from the sprint week. Can you take a look at it?

**Comment by jsouth** [comment]
@ChristopherBiscardi - Sure thing, on it.

**Comment by gopalfreak** [comment]
![searchbox_ff](https://cloud.githubusercontent.com/assets/8685067/8126594/29277afc-10f0-11e5-9024-14722f58c71d.JPG)
![searchbox_chrome](https://cloud.githubusercontent.com/assets/8685067/8126595/2af16532-10f0-11e5-85d2-d166ed04ae2d.JPG)
In actual Chrome Version 43.0.2357.124 m
(see screenshot) this doesn't appear - but I have the same issue in 3805 in FF like kibitz.

**Comment by ChristopherBiscardi** [comment]
Looks like this was fixed in the most recent deploy.
