### ISSUE TITLE
Search doesn't work if not logged in

### ISSUE THREAD

**Issue by nathanleclaire** [docker/hub-beta-feedback#71]
Steps to reproduce:

1. Go to https://hub-beta.docker.com/ (use Incognito mode if logged in)
2. Attempt to search in upper right hand corner

Expected result: It works
Actual result: Nothing happens

cc @ChristopherBiscardi

**Comment by nathanleclaire** [comment]
Update: This seems to work by default, my issue seems to be related to using https://hub-beta.docker.com/? as the URL?

**Comment by nathanleclaire** [comment]
Yeah, it works normally, but not if a question mark is appended to the end.

**Comment by ChristopherBiscardi** [comment]
Looks good in prod. Closing
