### ISSUE TITLE
Accessing invalid repo URLs should render 404, not view "/" repository

### ISSUE THREAD

**Issue by ewindisch** [docker/hub-beta-feedback#74]
Experienced:
When accessing an invalid repo, users are given view of a "/" repo.

Expected:
A 404 page.

**Comment by ewindisch** [comment]
I experienced this after clicking the link created in a repo's README markdown:

```
[id]

[id]: ~/settings "Optional Title Here"
```

**Comment by ChristopherBiscardi** [comment]
This is deployed
