### ISSUE TITLE
Accessing /r should give a 404 page (not *blank*)

### ISSUE THREAD

**Issue by ewindisch** [docker/hub-beta-feedback#75]
To reproduce:

Receiving a black page on /r

Expected:

A 404 page

![screen shot 2015-06-16 at 3 04 43 pm](https://cloud.githubusercontent.com/assets/73207/8191977/2d3e6bea-1439-11e5-9258-4cda4756226e.png)

**Comment by rrarunan** [comment]
Deployed to beta.
