### ISSUE TITLE
Links in markdown break javascript

### ISSUE THREAD

**Issue by ewindisch** [docker/hub-beta-feedback#76]
Cannot logout. Given a # page, no javascript seems to trigger.

![](http://g.recordit.co/V4uantFbkl.gif)

**Comment by ewindisch** [comment]
Uncaught SyntaxError: Unexpected token <

Force-reloading seemed to fix it. Close?

**Comment by ChristopherBiscardi** [comment]
This seems to be a routing issue relating to the way static asset urls (which are currently being served from the application server) are handled.

**Comment by rrarunan** [comment]
I haven't been able to repro this in the latest deploy and like @ChristopherBiscardi says, it could be because of a deployment issue. Closing this @ewindisch.

**Comment by ChristopherBiscardi** [comment]
FTR: This was due to some old html being served and the js bundle being requested from a different server, which meant it fell through.
