### ISSUE TITLE
Orgs added to teams create list entries with URL that always throws 404

### ISSUE THREAD

**Issue by ewindisch** [docker/hub-beta-feedback#79]
Adding an org to a team creates a link that gives a 404:

![](http://g.recordit.co/JlsyTWg8Xs.gif)

**Comment by rrarunan** [comment]
So, `/u/<org>` is the correct URL, but there is an issue with how we handle organization profiles at the moment. We will consider it this bug, where we get a 404 on organization profile pages and fix this.

**Comment by rrarunan** [comment]
I'm closing this as a duplicate of #45 .
