### ISSUE TITLE
Organization Username should be Organization Name

### ISSUE THREAD

**Issue by kizbitz** [docker/hub-beta-feedback#8]
When creating a new org it seems that:
- Organization Username: What user account should be associated with the new org.
- Organization Name: What is the name of the the new organization.

But it's backwards
![screen shot 2015-06-04 at 10 32 38 am](https://cloud.githubusercontent.com/assets/201920/7986371/4615e456-0aa5-11e5-95d1-256b96fc3749.png)

When I reverse the two entries the new org is created.

**Comment by rrarunan** [comment]
I believe, we cannot remove the field, we can rename it instead. Because, there needs to be a unique organization name as well. 

We are going to rename `Organization Username` -> `Organization Namespace`

**Comment by ChristopherBiscardi** [comment]
There are two fields being talked about. In the API these are referred to as `full_name` and `orgname`.

* `orgname` (Labelled in the UI as `Organization Username`)
  - The Namespace of an organization
  - ex: "myorg" in `myorg/myrepo`
* `full_name` (Labelled in the UI as `Organization Name`)
  - The Display Name of the Organization
  - ex: `My Awesome Organization`

I propose that we label the fields `Namespace` and `Organization Display Name` accordingly.

@rrarunan @kizbitz What do you think of the proposed solution?

**Comment by rrarunan** [comment]
@ChristopherBiscardi I'm thinking`orgname` -> `Organization Namespace` and `full_name`->`Organization Name`

**Comment by kizbitz** [comment]
'Organization Namespace' and 'Organization Display Name' (or just 'Display Name') is the clearest to me.

**Comment by rrarunan** [comment]
Changed to `Namespace` and `Full Name`. Please report back if its not ideal.
