### ISSUE TITLE
Add image size on tags

### ISSUE THREAD

**Issue by smougenot** [docker/hub-beta-feedback#81]
It would be nice to have an indication of the image on the tag view.
Might help track changes

**Comment by ChristopherBiscardi** [comment]
Image Sizes have been added to the tag view. Please not that this is not the final implementation and will continue to evolve as we move towards GA.

Example: https://hub-beta.docker.com/r/library/ubuntu/tags/

![screenshot 2015-06-23 00 55 08](https://cloud.githubusercontent.com/assets/551247/8301418/86f4d4f4-1942-11e5-8687-b10c311e5fdf.png)

**Comment by smougenot** [comment]
Great that's an improvement.
Just to a little think,
On the actual view (at the moment), the size is displayed in a way that get all the attention.
Making, difficult to focus on the real information of the view (tags on the tags view).

I would be nice to have the displayed size more discreat (text smaller than the one for the tag, color                                                                                                                                                                                                                                                                              maybe like the text in the title 'DESCRIPTION')

**Comment by ChristopherBiscardi** [comment]
Thanks for your feedback :)

The in-progress version (which hasn't been deployed yet) looks more like this:

![ubuntu-tags](https://cloud.githubusercontent.com/assets/551247/8316150/f1794f96-19a9-11e5-9e9d-5d1aef38468d.png)
