### ISSUE TITLE
Dockerfile for automated builds not displayed when user not logged in

### ISSUE THREAD

**Issue by nathanleclaire** [docker/hub-beta-feedback#82]
Steps to reproduce:

1. Go to Incognito in browser
2. Navigate to URL of automated build Dockerfile, e.g. https://hub-beta.docker.com/r/nuagebec/etcd/~/dockerfile/

Expected: Can see Dockerfile
Actual: Cannot see Dockerfile

Example:

![](https://cloud.githubusercontent.com/assets/1476820/8189807/a52ce0da-1413-11e5-90b4-c06fda5bff80.png)

cc @ChristopherBiscardi

**Comment by nhsiehgit** [comment]
We should update the API's to not require a user token in order to return the Dockerfile. Or at least set up another endpoint to get the dockerfiles if no token is provided.

**Comment by rrarunan** [comment]
^ sgtm. also need to verify if we get it fine.

**Comment by ChristopherBiscardi** [comment]
Confirmed that this is now visible when not logged in
