### ISSUE TITLE
Inconsistent wording on billing plans page

### ISSUE THREAD

**Issue by fredlf** [docker/hub-beta-feedback#83]
Two issues with the text on the billing plans page (see screenshot).

1. In the table detailing the plans, we have a column labeled "Private Images". However, throughout the docs and UI (including the text on this page) we refer to "private repositories".

2. The answer to the question "Do I have to pay to use your service?" is not accurate. It should be: "No, you only need to pay if you require more than one private repository."

![hub2-billing_plans](https://cloud.githubusercontent.com/assets/1459582/8215434/990a6008-14e4-11e5-90a8-b14dece33b79.png)

**Comment by ChristopherBiscardi** [comment]
deployed
