### ISSUE TITLE
No 404 and logout for invalid URL.

### ISSUE THREAD

**Issue by fredlf** [docker/hub-beta-feedback#85]
Enter an invalid Hub URL (e.g., https://hub-beta.docker.com/foo/), page returns blank and you get logged out.

Retuned Page source: 

`<html><head><meta charset="utf-8"><title></title><meta name="viewport" content="width=device-width, user-scalable=no"><link rel="stylesheet" href="/public/styles/main.css"></head><body><div id="app"><noscript data-reactid=".1iblttynugw" data-react-checksum="-1005252092"></noscript></div></body><script>window.App={"context":{"dispatcher":{"stores":{}},"plugins":{}},"plugins":{}};</script><script src="https://js.recurly.com/v3/recurly.js"></script><script src="/public/js/client.55317edf7bedc1253fc2.js" defer></script><script>window.loop11_key = "93a2e5ac4a3e4d3d635de091f13d81213a7989be"</script><script src="https://cdn.loop11.com/my/loop11.js" type="text/javascript"></script></html>`

**Comment by rrarunan** [comment]
deployed to beta.
