### ISSUE TITLE
Illegal repo names have no error messages, quietly fail to submit

### ISSUE THREAD

**Issue by mechfish** [docker/hub-beta-feedback#86]
Noting that the beta version of the new-repo form didn't have the instructions that the old form does, I tried creating a repo named foo*bar. Nothing happened... except that when I clicked the submit button, it didn't work. I pressed it three or four times, nothing. Then I edited the name to "foobar" and suddenly the button works.

I don't think the page needs to be cluttered up with old instructions, but it does need the apparently-missing-in-action Javascript-powered popup that tells me why my form won't submit!

Best of luck!

**Comment by nhsiehgit** [comment]
Thanks @mechfish! Was this from just creating a new repo or was it creating an automated build?

**Comment by ChristopherBiscardi** [comment]
@nhsiehgit it's an issue with the normal repo create form because of the special-cased repo name field.

**Comment by mechfish** [comment]
This was a new repo; I didn't try automated builds.

**Comment by rrarunan** [comment]
deployed.
