### ISSUE TITLE
URLs for deleted repositories can still be visited?

### ISSUE THREAD

**Issue by mechfish** [docker/hub-beta-feedback#87]
I deleted my (private) test repo, https://hub-beta.docker.com/r/mechfish/foobar/ , using the old hub site, and for fun I decided to reload its page on the new hub site, and there the page is! All its fields seem to be set to null, but it's there. Its title shows up as a single slash, "/". The links don't work (it seems to substitute in that single slash into the URLs.)

I tried to submit a comment to the nonexistent repo, and it vanished away without trace into the void, which I guess is not a terrible behavior. What else did I expect?

Technically, I did not check the return status code. I suppose it could be returning a 404 page but also rendering the template. Stranger things have happened in web apps.

**Comment by nhsiehgit** [comment]
Currently, navigating to any non-existant repo page, we provide an empty shell.
We should handle cases like this and redirect to a 404 or just the dashboard page or something.

Thanks for filing the issue!

**Comment by ChristopherBiscardi** [comment]
fixed in prod
