### ISSUE TITLE
this.props.tags.map is not a function

### ISSUE THREAD

**Issue by tonyhb** [docker/hub-beta-feedback#90]
On a private repo, hitting the Tabs map causes an Option and Get XHR request.  Once the Get XHR returns, this error occurs:

`client.ce6f4ce85fc587a5d4dd.js:425 Uncaught TypeError: this.props.tags.map is not a function`.

Happens somewhere in the `RepositoryDetailsTags` class.

**Comment by ChristopherBiscardi** [comment]
This one's my fault. I borked the clean forward-roll and we had to wait for the new APIs to deploy. It should no longer be an issue.
