### ISSUE TITLE
can't create private repo

### ISSUE THREAD

**Issue by tpaz** [docker/hub-beta-feedback#98]
filled all fields for an Organization repo. Clicking Create does not respond in any way. nothing happens

**Comment by tpaz** [comment]
Public does work.
probably because not allowed if not a paying  customer? need to add an alert popup or disable the private option as long as user is not a paid account...

**Comment by ChristopherBiscardi** [comment]
Thanks for reporting.

This is a known issue relating to the form-feedback mechanisms. We need to display the "out of private repos, here's where you can get more" style error message here (as well as in-progress indicators such as we have on login).

That said, all Users get 1 free private repo (Organizations do not), so it should work if you don't already have one on a User account.

**Comment by tpaz** [comment]
ok, good to know.
thanks for the quick revert.

On Fri, Jun 19, 2015 at 5:23 PM, Christopher Biscardi <
notifications@github.com> wrote:

> Thanks for reporting.
>
> This is a known issue relating to the form-feedback mechanisms. We need to
> display the "out of private repos, here's where you can get more" style
> error message here (as well as in-progress indicators such as we have on
> login).
>
> That said, all Users get 1 free private repo (Organizations do not), so it
> should work if you don't already have one on a User account.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/hub-beta-feedback/issues/98#issuecomment-113530087>
> .
>



-- 

Rgrds
Tomer

**Comment by rrarunan** [comment]
deployed. closing.
